--liquibase formatted sql
--changeset codex:13-enrich-language-metadata dbms:postgresql
--comment Enrich language metadata from ISO datasets and Wikidata. Updates only empty fields.

WITH data (
    iso639_3,
    iso639_1,
    iso639_2b,
    iso639_2t,
    english_name,
    native_name,
    language_family,
    writing_systems,
    direction,
    language_type,
    speakers_total,
    has_wikipedia
) AS (
    VALUES
        ('afr', 'af', 'afr', 'afr', 'Afrikaans', 'Afrikaans', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 10300000, TRUE),
        ('amh', 'am', 'amh', 'amh', 'Amharic', 'አማርኛ', NULL, '["Geʽez script"]'::jsonb, 'ltr', 'living', 21900000, TRUE),
        ('ara', 'ar', 'ara', 'ara', 'Arabic', 'اللُّغَة العَرَبِيّة', NULL, '["Arabic Braille", "Arabic alphabet", "Arabic script"]'::jsonb, 'rtl', 'living', 315421300, TRUE),
        ('arc', NULL, 'arc', 'arc', 'Official Aramaic (700-300 BCE)', NULL, NULL, NULL, NULL, 'ancient', NULL, NULL),
        ('aym', 'ay', 'aym', 'aym', 'Aymara', 'Aymar aru', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 4000000, TRUE),
        ('aze', 'az', 'aze', 'aze', 'Azerbaijani', 'Azərbaycan dili', NULL, '["Arabic alphabet", "Azerbaijani Braille", "Cyrillic script", "Latin script", "Persian alphabet"]'::jsonb, 'ltr', 'living', 23000000, TRUE),
        ('bel', 'be', 'bel', 'bel', 'Belarusian', 'беларуская мова', NULL, '["Belarusian Cyrillic alphabet"]'::jsonb, 'ltr', 'living', 7600000, TRUE),
        ('ben', 'bn', 'ben', 'ben', 'Bengali', 'বাংলা', NULL, '["Bangla alphabet", "Bengali Braille"]'::jsonb, 'ltr', 'living', 300000000, TRUE),
        ('ber', NULL, 'ber', 'ber', 'Berber languages', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        ('bis', 'bi', 'bis', 'bis', 'Bislama', 'Bislama', 'English-based creole languages', '["Avoiuli", "Latin script"]'::jsonb, 'ltr', 'living', 10000, TRUE),
        ('bjz', NULL, NULL, NULL, 'Baruga', NULL, NULL, NULL, NULL, 'living', NULL, NULL),
        ('bos', 'bs', 'bos', 'bos', 'Bosnian', 'bosanski', NULL, '["Gaj''s Latin alphabet"]'::jsonb, 'ltr', 'living', 3500000, TRUE),
        ('bul', 'bg', 'bul', 'bul', 'Bulgarian', 'български език', NULL, '["Bulgarian Braille", "Bulgarian alphabet", "Cyrillic script"]'::jsonb, 'ltr', 'living', 9000000, TRUE),
        ('bwg', NULL, NULL, NULL, 'Barwe', NULL, NULL, NULL, NULL, 'living', NULL, NULL),
        ('cat', 'ca', 'cat', 'cat', 'Catalan', 'català', NULL, '["Catalan Braille", "Catalan alphabet"]'::jsonb, 'ltr', 'living', 4873396, TRUE),
        ('ces', 'cs', 'cze', 'ces', 'Czech', 'čeština', 'Czech–Slovak languages', '["Czech Braille", "Czech alphabet"]'::jsonb, 'ltr', 'living', 10700000, TRUE),
        ('ckb', NULL, NULL, NULL, 'Central Kurdish', 'کوردی', NULL, '["Arabic alphabet", "Arabic script", "Kurdish Arabic alphabet", "Kurdish alphabets"]'::jsonb, 'rtl', 'living', 7250000, TRUE),
        ('cnr', NULL, 'cnr', 'cnr', 'Montenegrin', 'crnogorski jezik', NULL, '["Montenegrin Cyrillic alphabet", "Montenegrin Latin alphabet"]'::jsonb, 'ltr', 'living', 232600, TRUE),
        ('crs', NULL, NULL, NULL, 'Seselwa Creole French', NULL, 'French-based creole languages', '["Latin script"]'::jsonb, 'ltr', 'living', 73000, TRUE),
        ('dan', 'da', 'dan', 'dan', 'Danish', 'dansk', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 6000000, TRUE),
        ('deu', 'de', 'ger', 'deu', 'German', 'Deutsch', NULL, '["German Braille", "German alphabet"]'::jsonb, 'ltr', 'living', 76540740, TRUE),
        ('div', 'dv', 'div', 'div', 'Dhivehi', 'ދިވެހި', NULL, '["Dhives Akuru", "Thaana"]'::jsonb, 'rtl', 'living', 340500, TRUE),
        ('dzo', 'dz', 'dzo', 'dzo', 'Dzongkha', 'རྫོང་ཁ་', NULL, '["Tibetan alphabet"]'::jsonb, 'ltr', 'living', 237080, TRUE),
        ('ell', 'el', 'gre', 'ell', 'Modern Greek (1453-)', 'Ελληνικά', NULL, '["Greek alphabet"]'::jsonb, 'ltr', 'living', 15000000, TRUE),
        ('eng', 'en', 'eng', 'eng', 'English', 'English', NULL, '["English Braille", "English alphabet", "Unified English Braille"]'::jsonb, 'ltr', 'living', 753359540, TRUE),
        ('est', 'et', 'est', 'est', 'Estonian', 'eesti keel', NULL, '["Estonian Braille", "Latin script"]'::jsonb, 'ltr', 'living', 1251770, TRUE),
        ('eus', 'eu', 'baq', 'eus', 'Basque', 'Euskara', 'Basque languages', '["Basque alphabet", "Latin script"]'::jsonb, 'ltr', 'living', 750000, TRUE),
        ('fas', 'fa', 'per', 'fas', 'Persian', 'فارسی', NULL, '["Arabic script", "Persian alphabet"]'::jsonb, 'rtl', 'living', 45000000, TRUE),
        ('fij', 'fj', 'fij', 'fij', 'Fijian', 'vosa Vakaviti', NULL, '["Devanagari", "Latin script"]'::jsonb, 'ltr', 'living', 341270, TRUE),
        ('fil', NULL, 'fil', 'fil', 'Filipino', NULL, NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 90000000, NULL),
        ('fin', 'fi', 'fin', 'fin', 'Finnish', 'suomi', NULL, '["Latin script", "Scandinavian Braille"]'::jsonb, 'ltr', 'living', 5413380, TRUE),
        ('fra', 'fr', 'fre', 'fra', 'French', 'français', NULL, '["French Braille", "French alphabet"]'::jsonb, 'ltr', 'living', 208157220, TRUE),
        ('gil', NULL, 'gil', 'gil', 'Gilbertese', 'Taetae ni Kiribati', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 116280, TRUE),
        ('glc', NULL, NULL, NULL, 'Bon Gula', NULL, NULL, NULL, NULL, 'living', NULL, NULL),
        ('gle', 'ga', 'gle', 'gle', 'Irish', 'Gaeilge', NULL, '["Gaelic type", "Irish Braille", "Latin script"]'::jsonb, 'ltr', 'living', 141000, TRUE),
        ('grn', 'gn', 'grn', 'grn', 'Guarani', 'Avañe''ẽ', NULL, '["Guarani Braille", "Guarani alphabet"]'::jsonb, 'ltr', 'living', 4500000, TRUE),
        ('gsw', NULL, 'gsw', 'gsw', 'Swiss German', 'Alemannisch', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 10000000, TRUE),
        ('hat', 'ht', 'hat', 'hat', 'Haitian', 'Kreyòl ayisyen', 'Caribbean French Creole languages', '["Latin script"]'::jsonb, 'ltr', 'living', 9600000, TRUE),
        ('heb', 'he', 'heb', 'heb', 'Hebrew', 'עברית', 'Jewish languages', '["Hebrew alphabet"]'::jsonb, 'rtl', 'living', 9303950, TRUE),
        ('her', 'hz', 'her', 'her', 'Herero', 'Otjiherero', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 237000, TRUE),
        ('hgm', NULL, NULL, NULL, 'Haiǁom', NULL, NULL, NULL, NULL, 'living', NULL, NULL),
        ('hif', NULL, NULL, NULL, 'Fiji Hindi', 'Fiji Baat', NULL, '["Devanagari"]'::jsonb, 'ltr', 'living', 380000, TRUE),
        ('hin', 'hi', 'hin', 'hin', 'Hindi', 'हिन्दी', NULL, '["Devanagari"]'::jsonb, 'ltr', 'living', 341000000, TRUE),
        ('hmo', 'ho', 'hmo', 'hmo', 'Hiri Motu', 'Hiri Motu', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 180000, TRUE),
        ('hrv', 'hr', 'hrv', 'hrv', 'Croatian', 'hrvatski', NULL, '["Gaj''s Latin alphabet"]'::jsonb, 'ltr', 'living', 7000000, TRUE),
        ('hun', 'hu', 'hun', 'hun', 'Hungarian', 'magyar', NULL, '["Hungarian Braille", "Hungarian alphabet", "Old Hungarian"]'::jsonb, 'ltr', 'living', 12600000, TRUE),
        ('hye', 'hy', 'arm', 'hye', 'Armenian', 'հայերեն', NULL, '["Armenian alphabet"]'::jsonb, 'ltr', 'living', 6700000, TRUE),
        ('ind', 'id', 'ind', 'ind', 'Indonesian', 'Bahasa Indonesia', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 198996550, TRUE),
        ('isl', 'is', 'ice', 'isl', 'Icelandic', 'Íslenska', NULL, '["Icelandic Braille", "Icelandic alphabet", "Latin script"]'::jsonb, 'ltr', 'living', 321040, TRUE),
        ('ita', 'it', 'ita', 'ita', 'Italian', 'italiano', NULL, '["Italian Braille", "Italian alphabet"]'::jsonb, 'ltr', 'living', 64800000, TRUE),
        ('jam', NULL, NULL, NULL, 'Jamaican Creole English', 'Patwa', NULL, '["Cassidy/JLU orthography", "Latin script"]'::jsonb, 'ltr', 'living', 3200000, TRUE),
        ('jpn', 'ja', 'jpn', 'jpn', 'Japanese', '日本語', NULL, '["hiragana", "kana", "kanji", "katakana"]'::jsonb, 'ltr', 'living', 128000000, TRUE),
        ('kat', 'ka', 'geo', 'kat', 'Georgian', 'ქართული', NULL, '["Asomtavruli", "Georgian Braille", "Georgian scripts", "Mkhedruli", "Nuskhuri"]'::jsonb, 'ltr', 'living', 3700000, TRUE),
        ('kaz', 'kk', 'kaz', 'kaz', 'Kazakh', 'қазақша', NULL, '["Arabic alphabet", "Cyrillic script", "Kazakh Braille", "Latin script"]'::jsonb, 'ltr', 'living', 12900000, TRUE),
        ('kck', NULL, NULL, NULL, 'Kalanga', NULL, 'Shona languages', NULL, NULL, 'living', NULL, NULL),
        ('khi', NULL, 'khi', 'khi', 'Khoisan languages', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        ('khm', 'km', 'khm', 'khm', 'Khmer', 'ខ្មែរ', NULL, '["Khmer"]'::jsonb, 'ltr', 'living', 16600000, TRUE),
        ('kin', 'rw', 'kin', 'kin', 'Kinyarwanda', 'Kinyarwanda', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 12100000, TRUE),
        ('kir', 'ky', 'kir', 'kir', 'Kirghiz', 'кыргызча', NULL, '["Arabic alphabet", "Cyrillic script"]'::jsonb, 'ltr', 'living', 4568480, TRUE),
        ('kon', 'kg', 'kon', 'kon', 'Kongo', 'kikongo', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 5016500, TRUE),
        ('kor', 'ko', 'kor', 'kor', 'Korean', '조선말', NULL, '["Hangul", "Hanja"]'::jsonb, 'ltr', 'living', 77300000, TRUE),
        ('kwn', NULL, NULL, NULL, 'Kwangali', NULL, NULL, NULL, NULL, 'living', NULL, NULL),
        ('lao', 'lo', 'lao', 'lao', 'Lao', 'ລາວ', NULL, '["Lao"]'::jsonb, 'ltr', 'living', 5225552, TRUE),
        ('lat', 'la', 'lat', 'lat', 'Latin', 'Lingua latina', NULL, '["Latin alphabet"]'::jsonb, 'ltr', 'ancient', NULL, TRUE),
        ('lav', 'lv', 'lav', 'lav', 'Latvian', 'latviešu valoda', NULL, '["Latvian Braille", "Latvian alphabet"]'::jsonb, 'ltr', 'living', 1500000, TRUE),
        ('lin', 'ln', 'lin', 'lin', 'Lingala', 'Lingala', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 20000000, TRUE),
        ('lit', 'lt', 'lit', 'lit', 'Lithuanian', 'Lietuviškai', NULL, '["Lithuanian Braille", "Lithuanian alphabet"]'::jsonb, 'ltr', 'living', 4000000, TRUE),
        ('loz', NULL, 'loz', 'loz', 'Lozi', NULL, NULL, '["Latin script", "Zambian Braille"]'::jsonb, 'ltr', 'living', 600000, TRUE),
        ('ltz', 'lb', 'ltz', 'ltz', 'Luxembourgish', 'Lëtzebuergesch', NULL, '["Luxembourgish Braille", "Luxembourgish alphabet"]'::jsonb, 'ltr', 'living', 391200, TRUE),
        ('lua', NULL, 'lua', 'lua', 'Luba-Lulua', 'Tshiluba', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 6300000, TRUE),
        ('mah', 'mh', 'mah', 'mah', 'Marshallese', 'Kajin Ṃajōḷ', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 61000, TRUE),
        ('mfe', NULL, NULL, NULL, 'Morisyen', NULL, 'French-based creole languages', '["Latin script"]'::jsonb, 'ltr', 'living', 600000, TRUE),
        ('mkd', 'mk', 'mac', 'mkd', 'Macedonian', 'македонски', NULL, '["Cyrillic script", "Macedonian alphabet"]'::jsonb, 'ltr', 'living', 2000000, TRUE),
        ('mlg', 'mg', 'mlg', 'mlg', 'Malagasy', 'Fiteny malagasy', NULL, '["Latin script", "Sorabe alphabet"]'::jsonb, 'ltr', 'living', 18000000, TRUE),
        ('mlt', 'mt', 'mlt', 'mlt', 'Maltese', 'Malti', NULL, '["Maltese Braille", "Maltese alphabet"]'::jsonb, 'ltr', 'living', 570000, TRUE),
        ('mon', 'mn', 'mon', 'mon', 'Mongolian', 'монгол хэл', NULL, '["Cyrillic script", "Mongolian"]'::jsonb, 'ltr', 'living', 5200000, TRUE),
        ('mri', 'mi', 'mao', 'mri', 'Maori', 'Māori', NULL, '["Māori Braille", "Māori writing system"]'::jsonb, 'ltr', 'living', 213849, TRUE),
        ('msa', 'ms', 'may', 'msa', 'Malay (macrolanguage)', 'Bahasa Melayu', NULL, '["Jawi", "Latin script", "Malay alphabet"]'::jsonb, 'ltr', 'living', 77000000, TRUE),
        ('mya', 'my', 'bur', 'mya', 'Burmese', 'မြန်မာဘာသာ', NULL, '["Burmese alphabet", "Mon–Burmese script"]'::jsonb, 'ltr', 'living', 32900000, TRUE),
        ('nau', 'na', 'nau', 'nau', 'Nauru', 'Dorerin Naoero', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 9300, TRUE),
        ('nbl', 'nr', 'nbl', 'nbl', 'South Ndebele', 'IsiNdebele', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 640000, TRUE),
        ('ndc', NULL, NULL, NULL, 'Ndau', NULL, 'Shona languages', NULL, NULL, 'living', NULL, NULL),
        ('nde', 'nd', 'nde', 'nde', 'North Ndebele', 'Sindebele', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 1572800, NULL),
        ('ndo', 'ng', 'ndo', 'ndo', 'Ndonga', 'Ndonga', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 810000, TRUE),
        ('nep', 'ne', 'nep', 'nep', 'Nepali (macrolanguage)', 'नेपाली', NULL, '["Devanagari"]'::jsonb, 'ltr', 'living', 15800000, TRUE),
        ('nld', 'nl', 'dut', 'nld', 'Dutch', 'Vlaams', NULL, '["Dutch alphabet", "Dutch eight-dot Braille", "Dutch six-dot Braille"]'::jsonb, 'ltr', 'living', 23100000, TRUE),
        ('nno', 'nn', 'nno', 'nno', 'Norwegian Nynorsk', 'Nynorsk', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 4320000, TRUE),
        ('nob', 'nb', 'nob', 'nob', 'Norwegian Bokmål', 'bokmål', NULL, '["Dano-Norwegian alphabet", "Latin script"]'::jsonb, 'ltr', 'living', 4000000, TRUE),
        ('nso', NULL, 'nso', 'nso', 'Pedi', 'Sepedi', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 4100000, TRUE),
        ('nya', 'ny', 'nya', 'nya', 'Nyanja', 'Chicheŵa', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 12000000, TRUE),
        ('nzs', NULL, NULL, NULL, 'New Zealand Sign Language', 'te reo Turi', NULL, NULL, NULL, 'sign', 20200, NULL),
        ('pau', NULL, 'pau', 'pau', 'Palauan', 'tekoi er a Belau', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 17000, NULL),
        ('pol', 'pl', 'pol', 'pol', 'Polish', 'polszczyzna', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 39700000, TRUE),
        ('por', 'pt', 'por', 'por', 'Portuguese', 'português', NULL, '["Latin script", "Portuguese alphabet"]'::jsonb, 'ltr', 'living', 254300000, TRUE),
        ('pov', NULL, NULL, NULL, 'Upper Guinea Crioulo', NULL, 'Portuguese-based creole languages', '["Latin script"]'::jsonb, 'ltr', 'living', 500000, NULL),
        ('prs', NULL, NULL, NULL, 'Dari', 'دری', NULL, '["Persian alphabet"]'::jsonb, 'rtl', 'living', 9600000, TRUE),
        ('pus', 'ps', 'pus', 'pus', 'Pushto', 'پښتو', NULL, '["Arabic alphabet", "Arabic script"]'::jsonb, 'rtl', 'living', 39000000, TRUE),
        ('que', 'qu', 'que', 'que', 'Quechua', 'Qhichwa simi', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 8900000, TRUE),
        ('roh', 'rm', 'roh', 'roh', 'Romansh', 'rumantsch', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 40039, TRUE),
        ('ron', 'ro', 'rum', 'ron', 'Romanian', 'românește', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 24300000, TRUE),
        ('run', 'rn', 'run', 'run', 'Rundi', 'Ikirundi', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 10800000, TRUE),
        ('rus', 'ru', 'rus', 'rus', 'Russian', 'русский язык', NULL, '["Cyrillic script"]'::jsonb, 'ltr', 'living', 154000000, TRUE),
        ('sag', 'sg', 'sag', 'sag', 'Sango', 'Sango', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 4600000, TRUE),
        ('sin', 'si', 'sin', 'sin', 'Sinhala', 'සිංහල', NULL, '["Sinhala script"]'::jsonb, 'ltr', 'living', 15300000, TRUE),
        ('slk', 'sk', 'slo', 'slk', 'Slovak', 'slovenčina', 'Czech–Slovak languages', '["Latin script"]'::jsonb, 'ltr', 'living', 6000000, TRUE),
        ('slv', 'sl', 'slv', 'slv', 'Slovenian', 'slovenščina', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 2400000, TRUE),
        ('smi', NULL, 'smi', 'smi', 'Sami languages', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
        ('smo', 'sm', 'smo', 'smo', 'Samoan', 'Gagana Samoa', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 415720, TRUE),
        ('sna', 'sn', 'sna', 'sna', 'Shona', 'ChiShona', 'Shona languages', '["Latin script"]'::jsonb, 'ltr', 'living', 8300000, TRUE),
        ('som', 'so', 'som', 'som', 'Somali', 'اف صومالِ', 'Somali languages', '["Latin script", "Osmanya", "Wadaad''s writing"]'::jsonb, 'ltr', 'living', 16200000, TRUE),
        ('sot', 'st', 'sot', 'sot', 'Southern Sotho', 'Sesotho', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 6000000, TRUE),
        ('spa', 'es', 'spa', 'spa', 'Spanish', 'español', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 485000000, TRUE),
        ('sqi', 'sq', 'alb', 'sqi', 'Albanian', 'Gjuha shqipe', NULL, '["Albanian alphabet"]'::jsonb, 'ltr', 'living', 6200000, TRUE),
        ('srp', 'sr', 'srp', 'srp', 'Serbian', 'српски', NULL, '["Gaj''s Latin alphabet", "Serbian Cyrillic alphabet"]'::jsonb, 'ltr', 'living', 9000000, TRUE),
        ('ssw', 'ss', 'ssw', 'ssw', 'Swati', 'Siswati', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 2034200, TRUE),
        ('swa', 'sw', 'swa', 'swa', 'Swahili (macrolanguage)', 'Kiswahili', NULL, '["Latin script", "Swahili Ajami"]'::jsonb, 'ltr', 'living', 15437390, TRUE),
        ('swe', 'sv', 'swe', 'swe', 'Swedish', 'svenska', NULL, '["Latin script", "Swedish alphabet"]'::jsonb, 'ltr', 'living', 9244250, TRUE),
        ('tam', 'ta', 'tam', 'tam', 'Tamil', 'தமிழ்', 'Tamil languages', '["Arabic script", "Koleluttu", "Tamil script", "Vatteluttu"]'::jsonb, 'ltr', 'living', 75000000, TRUE),
        ('tet', NULL, 'tet', 'tet', 'Tetum', 'Tetun', NULL, '["Latin script", "Tetum alphabet"]'::jsonb, 'ltr', 'living', 463500, TRUE),
        ('tgk', 'tg', 'tgk', 'tgk', 'Tajik', 'забони адабӣ', NULL, '["Cyrillic script", "Hebrew alphabet", "Latin script", "Persian alphabet", "Tajik Cyrillic alphabet"]'::jsonb, 'ltr', 'living', 14000000, TRUE),
        ('tha', 'th', 'tha', 'tha', 'Thai', 'ภาษาไทย', NULL, '["Thai script", "romanization of Thai"]'::jsonb, 'ltr', 'living', 20700000, TRUE),
        ('tir', 'ti', 'tir', 'tir', 'Tigrinya', 'ትግርኛ', NULL, '["Geʽez script"]'::jsonb, 'ltr', 'living', 7507780, TRUE),
        ('toi', NULL, NULL, NULL, 'Tonga (Zambia)', NULL, NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 1270000, NULL),
        ('ton', 'to', 'ton', 'ton', 'Tonga (Tonga Islands)', 'Faka Tonga', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 186010, TRUE),
        ('tpi', NULL, 'tpi', 'tpi', 'Tok Pisin', 'Tok Pisin', 'English-based creole languages', '["Latin script"]'::jsonb, 'ltr', 'living', 4000000, TRUE),
        ('tsn', 'tn', 'tsn', 'tsn', 'Tswana', 'seTswana', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 4500000, TRUE),
        ('tso', 'ts', 'tso', 'tso', 'Tsonga', 'Tsonga', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 13000000, TRUE),
        ('tuk', 'tk', 'tuk', 'tuk', 'Turkmen', 'Türkmen', NULL, '["Cyrillic script", "Latin script", "Perso-Arabic script", "Russian Braille", "Turkmen alphabet"]'::jsonb, 'ltr', 'living', 16000000, TRUE),
        ('tur', 'tr', 'tur', 'tur', 'Turkish', 'Türkçe', NULL, '["Turkish alphabet"]'::jsonb, 'ltr', 'living', 82231620, TRUE),
        ('tvl', NULL, 'tvl', 'tvl', 'Tuvalu', '‘Gana Tuvalu', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 13000, TRUE),
        ('ukr', 'uk', 'ukr', 'ukr', 'Ukrainian', 'українська мова', NULL, '["Cyrillic script"]'::jsonb, 'ltr', 'living', 26900000, TRUE),
        ('urd', 'ur', 'urd', 'urd', 'Urdu', 'اردو', NULL, '["Urdu orthography"]'::jsonb, 'rtl', 'living', 68600000, TRUE),
        ('uzb', 'uz', 'uzb', 'uzb', 'Uzbek', 'Ўзбек тили', NULL, '["Arabic alphabet", "Cyrillic script", "Latin script"]'::jsonb, 'ltr', 'living', 27000000, TRUE),
        ('ven', 've', 'ven', 'ven', 'Venda', 'Tshivenḓa', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 1300000, TRUE),
        ('vie', 'vi', 'vie', 'vie', 'Vietnamese', 'Tiếng Việt', NULL, '["Latin script", "Vietnamese Braille", "Vietnamese alphabet", "chữ Nôm"]'::jsonb, 'ltr', 'living', 76000000, TRUE),
        ('xho', 'xh', 'xho', 'xho', 'Xhosa', 'IsiXhosa', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 8177300, TRUE),
        ('zdj', NULL, NULL, NULL, 'Ngazidja Comorian', NULL, NULL, '["Arabic alphabet", "Latin script"]'::jsonb, 'ltr', 'living', 312000, NULL),
        ('zho', 'zh', 'chi', 'zho', 'Chinese', '中文', NULL, '["Chinese characters", "simplified Chinese characters", "traditional Chinese characters"]'::jsonb, 'ltr', 'living', 1299877520, TRUE),
        ('zib', NULL, NULL, NULL, 'Zimbabwe Sign Language', NULL, NULL, NULL, NULL, 'sign', 280000, NULL),
        ('zul', 'zu', 'zul', 'zul', 'Zulu', 'isiZulu', NULL, '["Latin script"]'::jsonb, 'ltr', 'living', 12100000, TRUE)
)
UPDATE language l
SET
    iso639_1 = COALESCE(NULLIF(l.iso639_1, ''), d.iso639_1),
    iso639_2b = COALESCE(NULLIF(l.iso639_2b, ''), d.iso639_2b),
    iso639_2t = COALESCE(NULLIF(l.iso639_2t, ''), d.iso639_2t),
    english_name = COALESCE(NULLIF(l.english_name, ''), d.english_name),
    native_name = COALESCE(NULLIF(l.native_name, ''), d.native_name),
    language_family = COALESCE(NULLIF(l.language_family, ''), d.language_family),
    writing_systems = COALESCE(l.writing_systems, d.writing_systems),
    direction = COALESCE(NULLIF(l.direction, ''), d.direction),
    language_type = COALESCE(NULLIF(l.language_type, ''), d.language_type),
    speakers_total = COALESCE(l.speakers_total, d.speakers_total),
    has_wikipedia = COALESCE(l.has_wikipedia, d.has_wikipedia),
    notes = COALESCE(NULLIF(l.notes, ''), 'Sources: /usr/share/iso-codes (ISO 639-2/3) + Wikidata P1705/P282/P1098/P424')
FROM data d
WHERE l.iso639_3 = d.iso639_3
  AND (
      l.iso639_1 IS NULL OR l.iso639_1 = ''
      OR l.iso639_2b IS NULL OR l.iso639_2b = ''
      OR l.iso639_2t IS NULL OR l.iso639_2t = ''
      OR l.english_name IS NULL OR l.english_name = ''
      OR l.native_name IS NULL OR l.native_name = ''
      OR l.language_family IS NULL OR l.language_family = ''
      OR l.writing_systems IS NULL
      OR l.direction IS NULL OR l.direction = ''
      OR l.language_type IS NULL OR l.language_type = ''
      OR l.speakers_total IS NULL
      OR l.has_wikipedia IS NULL
      OR l.notes IS NULL OR l.notes = ''
  );
