--liquibase formatted sql
--changeset codex:16-create-territory-table dbms:postgresql
--comment Create normalized territory table for admin divisions and regions.

CREATE TABLE IF NOT EXISTS territory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(32) NOT NULL,
    country_id BIGINT NOT NULL,
    parent_id BIGINT,
    wikidata_id VARCHAR(32),
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    CONSTRAINT pk_territory PRIMARY KEY (id),
    CONSTRAINT fk_territory_country FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
    CONSTRAINT fk_territory_parent FOREIGN KEY (parent_id) REFERENCES territory(id) ON DELETE SET NULL,
    CONSTRAINT uq_territory_wikidata_id UNIQUE (wikidata_id),
    CONSTRAINT chk_territory_type CHECK (
        type IN (
            'state',
            'province',
            'region',
            'department',
            'county',
            'district',
            'municipality',
            'autonomous_region',
            'overseas_region',
            'historical_region',
            'cultural_region'
        )
    ),
    CONSTRAINT chk_territory_wikidata_id CHECK (
        wikidata_id IS NULL OR wikidata_id ~ '^Q[0-9]+$'
    )
);

CREATE INDEX IF NOT EXISTS ix_territory_country_id ON territory(country_id);
CREATE INDEX IF NOT EXISTS ix_territory_parent_id ON territory(parent_id);
CREATE INDEX IF NOT EXISTS ix_territory_type ON territory(type);

COMMENT ON COLUMN territory.type IS
'Wikidata mapping: federal state->state, province->province, region->region, department->department, county->county, district->district, municipality->municipality, autonomous region->autonomous_region, overseas department/territory->overseas_region, historical region->historical_region, cultural region->cultural_region';
