--liquibase formatted sql

--changeset codex:25-create-country-admin-level-table dbms:postgresql
--comment Create per-country administrative level definitions.

CREATE TABLE IF NOT EXISTS country_admin_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country_id BIGINT NOT NULL,
    level_number SMALLINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(120) NOT NULL,
    default_territory_type_code VARCHAR(32),
    parent_level_id BIGINT,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_country_admin_level PRIMARY KEY (id),
    CONSTRAINT fk_country_admin_level_country
        FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
    CONSTRAINT fk_country_admin_level_parent
        FOREIGN KEY (parent_level_id) REFERENCES country_admin_level(id) ON DELETE SET NULL,
    CONSTRAINT fk_country_admin_level_default_territory_type
        FOREIGN KEY (default_territory_type_code) REFERENCES territory_type(code),
    CONSTRAINT uq_country_admin_level_country_level UNIQUE (country_id, level_number),
    CONSTRAINT uq_country_admin_level_country_code UNIQUE (country_id, code),
    CONSTRAINT chk_country_admin_level_code CHECK (code ~ '^[a-z0-9_]+$')
);

CREATE INDEX IF NOT EXISTS ix_country_admin_level_country_id
    ON country_admin_level(country_id);

CREATE INDEX IF NOT EXISTS ix_country_admin_level_parent_level_id
    ON country_admin_level(parent_level_id);

COMMENT ON TABLE country_admin_level IS
'Administrative hierarchy definition by country. This is the clean business hierarchy, separate from the broad territory gazetteer.';

COMMENT ON COLUMN country_admin_level.default_territory_type_code IS
'Optional hint for the most common territory.type backing this admin level. It is informational and not enforced.';

--changeset codex:25-create-admin-territory-table dbms:postgresql
--comment Create clean administrative hierarchy entries on top of territory.

CREATE TABLE IF NOT EXISTS admin_territory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country_id BIGINT NOT NULL,
    admin_level_id BIGINT NOT NULL,
    territory_id BIGINT NOT NULL,
    parent_admin_territory_id BIGINT,
    display_name TEXT NOT NULL,
    admin_code VARCHAR(64),
    admin_code_system VARCHAR(64),
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    is_official BOOLEAN NOT NULL DEFAULT TRUE,
    source VARCHAR(120) NOT NULL DEFAULT 'seed.country_admin_structure',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_territory PRIMARY KEY (id),
    CONSTRAINT fk_admin_territory_country
        FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_territory_admin_level
        FOREIGN KEY (admin_level_id) REFERENCES country_admin_level(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_territory_territory
        FOREIGN KEY (territory_id) REFERENCES territory(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_territory_parent
        FOREIGN KEY (parent_admin_territory_id) REFERENCES admin_territory(id) ON DELETE SET NULL,
    CONSTRAINT uq_admin_territory_country_level_territory UNIQUE (country_id, admin_level_id, territory_id),
    CONSTRAINT uq_admin_territory_country_level_code UNIQUE (country_id, admin_level_id, admin_code_system, admin_code),
    CONSTRAINT chk_admin_territory_code_pair CHECK (
        (admin_code IS NULL AND admin_code_system IS NULL)
        OR (admin_code IS NOT NULL AND admin_code_system IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_admin_territory_country_id
    ON admin_territory(country_id);

CREATE INDEX IF NOT EXISTS ix_admin_territory_admin_level_id
    ON admin_territory(admin_level_id);

CREATE INDEX IF NOT EXISTS ix_admin_territory_territory_id
    ON admin_territory(territory_id);

CREATE INDEX IF NOT EXISTS ix_admin_territory_parent_admin_territory_id
    ON admin_territory(parent_admin_territory_id);

COMMENT ON TABLE admin_territory IS
'Administrative territories curated on top of territory. Use this table for official country hierarchies instead of territory.type heuristics.';

COMMENT ON COLUMN admin_territory.display_name IS
'Canonical business-facing label for the administrative unit. It may be cleaner than the raw territory.name imported from Wikidata.';

COMMENT ON COLUMN admin_territory.admin_code IS
'Administrative code for the unit within the country, such as INSEE department codes in France.';

--changeset codex:25-create-admin-territory-view dbms:postgresql
--comment Convenience view to query clean administrative hierarchies with source territory metadata.

CREATE OR REPLACE VIEW v_admin_territory AS
SELECT
    at.id AS admin_territory_id,
    at.country_id,
    c.iso_code AS country_iso2,
    c.iso3_code AS country_iso3,
    at.admin_level_id,
    cal.level_number,
    cal.code AS admin_level_code,
    cal.label AS admin_level_label,
    at.territory_id,
    t.wikidata_id AS territory_wikidata_id,
    t.name AS territory_source_name,
    t.type AS territory_source_type,
    at.display_name,
    at.admin_code,
    at.admin_code_system,
    at.parent_admin_territory_id,
    parent_at.display_name AS parent_display_name,
    parent_at.admin_code AS parent_admin_code,
    parent_cal.code AS parent_admin_level_code,
    at.is_current,
    at.is_official,
    at.source
FROM admin_territory at
JOIN country_admin_level cal ON cal.id = at.admin_level_id
JOIN country c ON c.id = at.country_id
JOIN territory t ON t.id = at.territory_id
LEFT JOIN admin_territory parent_at ON parent_at.id = at.parent_admin_territory_id
LEFT JOIN country_admin_level parent_cal ON parent_cal.id = parent_at.admin_level_id;

--changeset codex:25-seed-france-admin-levels dbms:postgresql
--comment Seed the clean French administrative hierarchy definition.

WITH france AS (
    SELECT id
    FROM country
    WHERE iso_code = 'FR'
),
seed(level_number, code, label, default_territory_type_code) AS (
    VALUES
        (1, 'region', 'Region', 'region'),
        (2, 'department', 'Departement', 'department'),
        (3, 'arrondissement', 'Arrondissement', 'district'),
        (4, 'canton', 'Canton', NULL),
        (5, 'commune', 'Commune', 'municipality')
)
INSERT INTO country_admin_level (
    country_id,
    level_number,
    code,
    label,
    default_territory_type_code,
    parent_level_id,
    is_current
)
SELECT
    f.id,
    s.level_number,
    s.code,
    s.label,
    s.default_territory_type_code,
    NULL,
    TRUE
FROM france f
CROSS JOIN seed s
ON CONFLICT (country_id, code) DO UPDATE
SET
    level_number = EXCLUDED.level_number,
    label = EXCLUDED.label,
    default_territory_type_code = EXCLUDED.default_territory_type_code,
    is_current = EXCLUDED.is_current;

WITH france AS (
    SELECT id
    FROM country
    WHERE iso_code = 'FR'
),
parent_seed(child_code, parent_code) AS (
    VALUES
        ('department', 'region'),
        ('arrondissement', 'department'),
        ('canton', 'department'),
        ('commune', 'department')
)
UPDATE country_admin_level child
SET parent_level_id = parent.id
FROM france f
JOIN parent_seed ps ON TRUE
JOIN country_admin_level parent
    ON parent.country_id = f.id
   AND parent.code = ps.parent_code
WHERE child.country_id = f.id
  AND child.code = ps.child_code;
