--liquibase formatted sql

--changeset codex:26-load-country-admin-levels dbms:postgresql
--comment Seed inferred administrative level definitions for all countries except France from the normalized territory snapshot.

WITH seed(country_iso, level_number, code, label, default_territory_type_code, parent_code) AS (
    VALUES
        ('AD', 1, 'region', 'Region', 'region', NULL),
        ('AD', 2, 'province', 'Province', 'province', 'region'),
        ('AD', 3, 'department', 'Department', 'department', 'province'),
        ('AD', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('AE', 1, 'region', 'Region', 'region', NULL),
        ('AE', 2, 'province', 'Province', 'province', 'region'),
        ('AE', 3, 'department', 'Department', 'department', 'province'),
        ('AE', 4, 'district', 'District', 'district', 'department'),
        ('AF', 1, 'region', 'Region', 'region', NULL),
        ('AF', 2, 'department', 'Department', 'department', 'region'),
        ('AF', 3, 'district', 'District', 'district', 'department'),
        ('AG', 1, 'region', 'Region', 'region', NULL),
        ('AG', 2, 'department', 'Department', 'department', 'region'),
        ('AL', 1, 'region', 'Region', 'region', NULL),
        ('AL', 2, 'province', 'Province', 'province', 'region'),
        ('AL', 3, 'department', 'Department', 'department', 'province'),
        ('AL', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('AM', 1, 'region', 'Region', 'region', NULL),
        ('AM', 2, 'department', 'Department', 'department', 'region'),
        ('AM', 3, 'district', 'District', 'district', 'department'),
        ('AM', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('AO', 1, 'region', 'Region', 'region', NULL),
        ('AO', 2, 'province', 'Province', 'province', 'region'),
        ('AO', 3, 'department', 'Department', 'department', 'province'),
        ('AO', 4, 'district', 'District', 'district', 'department'),
        ('AO', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('AR', 1, 'region', 'Region', 'region', NULL),
        ('AR', 2, 'province', 'Province', 'province', 'region'),
        ('AR', 3, 'department', 'Department', 'department', 'province'),
        ('AR', 4, 'district', 'District', 'district', 'department'),
        ('AR', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('AT', 1, 'region', 'Region', 'region', NULL),
        ('AT', 2, 'province', 'Province', 'province', 'region'),
        ('AT', 3, 'department', 'Department', 'department', 'province'),
        ('AT', 4, 'district', 'District', 'district', 'department'),
        ('AT', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('AU', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('AU', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('AU', 3, 'province', 'Province', 'province', 'region'),
        ('AU', 4, 'department', 'Department', 'department', 'province'),
        ('AU', 5, 'county', 'County', 'county', 'department'),
        ('AU', 6, 'district', 'District', 'district', 'county'),
        ('AU', 7, 'municipality', 'Municipality', 'municipality', 'district'),
        ('AZ', 1, 'region', 'Region', 'region', NULL),
        ('AZ', 2, 'department', 'Department', 'department', 'region'),
        ('AZ', 3, 'district', 'District', 'district', 'department'),
        ('AZ', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BA', 1, 'region', 'Region', 'region', NULL),
        ('BA', 2, 'province', 'Province', 'province', 'region'),
        ('BA', 3, 'department', 'Department', 'department', 'province'),
        ('BA', 4, 'district', 'District', 'district', 'department'),
        ('BA', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BB', 1, 'region', 'Region', 'region', NULL),
        ('BB', 2, 'department', 'Department', 'department', 'region'),
        ('BD', 1, 'region', 'Region', 'region', NULL),
        ('BD', 2, 'province', 'Province', 'province', 'region'),
        ('BD', 3, 'department', 'Department', 'department', 'province'),
        ('BD', 4, 'district', 'District', 'district', 'department'),
        ('BD', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BE', 1, 'region', 'Region', 'region', NULL),
        ('BE', 2, 'province', 'Province', 'province', 'region'),
        ('BE', 3, 'department', 'Department', 'department', 'province'),
        ('BE', 4, 'district', 'District', 'district', 'department'),
        ('BE', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BF', 1, 'region', 'Region', 'region', NULL),
        ('BF', 2, 'province', 'Province', 'province', 'region'),
        ('BF', 3, 'department', 'Department', 'department', 'province'),
        ('BF', 4, 'district', 'District', 'district', 'department'),
        ('BF', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BG', 1, 'region', 'Region', 'region', NULL),
        ('BG', 2, 'province', 'Province', 'province', 'region'),
        ('BG', 3, 'department', 'Department', 'department', 'province'),
        ('BG', 4, 'district', 'District', 'district', 'department'),
        ('BG', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BH', 1, 'region', 'Region', 'region', NULL),
        ('BH', 2, 'department', 'Department', 'department', 'region'),
        ('BH', 3, 'district', 'District', 'district', 'department'),
        ('BI', 1, 'region', 'Region', 'region', NULL),
        ('BI', 2, 'province', 'Province', 'province', 'region'),
        ('BI', 3, 'district', 'District', 'district', 'province'),
        ('BI', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BJ', 1, 'region', 'Region', 'region', NULL),
        ('BJ', 2, 'province', 'Province', 'province', 'region'),
        ('BJ', 3, 'department', 'Department', 'department', 'province'),
        ('BJ', 4, 'district', 'District', 'district', 'department'),
        ('BJ', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BN', 1, 'region', 'Region', 'region', NULL),
        ('BN', 2, 'department', 'Department', 'department', 'region'),
        ('BN', 3, 'municipality', 'Municipality', 'municipality', 'department'),
        ('BO', 1, 'region', 'Region', 'region', NULL),
        ('BO', 2, 'province', 'Province', 'province', 'region'),
        ('BO', 3, 'department', 'Department', 'department', 'province'),
        ('BO', 4, 'district', 'District', 'district', 'department'),
        ('BO', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BR', 1, 'region', 'Region', 'region', NULL),
        ('BR', 2, 'province', 'Province', 'province', 'region'),
        ('BR', 3, 'department', 'Department', 'department', 'province'),
        ('BR', 4, 'district', 'District', 'district', 'department'),
        ('BR', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BS', 1, 'region', 'Region', 'region', NULL),
        ('BS', 2, 'province', 'Province', 'province', 'region'),
        ('BS', 3, 'department', 'Department', 'department', 'province'),
        ('BS', 4, 'district', 'District', 'district', 'department'),
        ('BS', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('BT', 1, 'region', 'Region', 'region', NULL),
        ('BT', 2, 'department', 'Department', 'department', 'region'),
        ('BT', 3, 'district', 'District', 'district', 'department'),
        ('BW', 1, 'region', 'Region', 'region', NULL),
        ('BW', 2, 'department', 'Department', 'department', 'region'),
        ('BY', 1, 'region', 'Region', 'region', NULL),
        ('BY', 2, 'province', 'Province', 'province', 'region'),
        ('BY', 3, 'department', 'Department', 'department', 'province'),
        ('BY', 4, 'district', 'District', 'district', 'department'),
        ('BZ', 1, 'region', 'Region', 'region', NULL),
        ('BZ', 2, 'department', 'Department', 'department', 'region'),
        ('BZ', 3, 'district', 'District', 'district', 'department'),
        ('BZ', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CA', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('CA', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('CA', 3, 'province', 'Province', 'province', 'region'),
        ('CA', 4, 'department', 'Department', 'department', 'province'),
        ('CA', 5, 'county', 'County', 'county', 'department'),
        ('CA', 6, 'district', 'District', 'district', 'county'),
        ('CA', 7, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CD', 1, 'region', 'Region', 'region', NULL),
        ('CD', 2, 'province', 'Province', 'province', 'region'),
        ('CD', 3, 'department', 'Department', 'department', 'province'),
        ('CD', 4, 'district', 'District', 'district', 'department'),
        ('CD', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CF', 1, 'region', 'Region', 'region', NULL),
        ('CF', 2, 'province', 'Province', 'province', 'region'),
        ('CF', 3, 'district', 'District', 'district', 'province'),
        ('CF', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CG', 1, 'region', 'Region', 'region', NULL),
        ('CG', 2, 'province', 'Province', 'province', 'region'),
        ('CG', 3, 'department', 'Department', 'department', 'province'),
        ('CG', 4, 'district', 'District', 'district', 'department'),
        ('CG', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CH', 1, 'region', 'Region', 'region', NULL),
        ('CH', 2, 'province', 'Province', 'province', 'region'),
        ('CH', 3, 'department', 'Department', 'department', 'province'),
        ('CH', 4, 'district', 'District', 'district', 'department'),
        ('CH', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CI', 1, 'region', 'Region', 'region', NULL),
        ('CL', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('CL', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('CL', 3, 'province', 'Province', 'province', 'region'),
        ('CL', 4, 'department', 'Department', 'department', 'province'),
        ('CL', 5, 'district', 'District', 'district', 'department'),
        ('CL', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CM', 1, 'region', 'Region', 'region', NULL),
        ('CM', 2, 'province', 'Province', 'province', 'region'),
        ('CM', 3, 'department', 'Department', 'department', 'province'),
        ('CM', 4, 'district', 'District', 'district', 'department'),
        ('CM', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CN', 1, 'region', 'Region', 'region', NULL),
        ('CN', 2, 'province', 'Province', 'province', 'region'),
        ('CN', 3, 'department', 'Department', 'department', 'province'),
        ('CN', 4, 'county', 'County', 'county', 'department'),
        ('CN', 5, 'district', 'District', 'district', 'county'),
        ('CN', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CO', 1, 'region', 'Region', 'region', NULL),
        ('CO', 2, 'province', 'Province', 'province', 'region'),
        ('CO', 3, 'department', 'Department', 'department', 'province'),
        ('CO', 4, 'district', 'District', 'district', 'department'),
        ('CO', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CR', 1, 'region', 'Region', 'region', NULL),
        ('CR', 2, 'province', 'Province', 'province', 'region'),
        ('CR', 3, 'district', 'District', 'district', 'province'),
        ('CR', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CU', 1, 'region', 'Region', 'region', NULL),
        ('CU', 2, 'province', 'Province', 'province', 'region'),
        ('CU', 3, 'department', 'Department', 'department', 'province'),
        ('CU', 4, 'district', 'District', 'district', 'department'),
        ('CU', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CV', 1, 'region', 'Region', 'region', NULL),
        ('CV', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('CY', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('CY', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('CY', 3, 'province', 'Province', 'province', 'region'),
        ('CY', 4, 'department', 'Department', 'department', 'province'),
        ('CY', 5, 'district', 'District', 'district', 'department'),
        ('CY', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('CZ', 1, 'region', 'Region', 'region', NULL),
        ('CZ', 2, 'province', 'Province', 'province', 'region'),
        ('CZ', 3, 'department', 'Department', 'department', 'province'),
        ('CZ', 4, 'district', 'District', 'district', 'department'),
        ('CZ', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('DE', 1, 'region', 'Region', 'region', NULL),
        ('DE', 2, 'province', 'Province', 'province', 'region'),
        ('DE', 3, 'department', 'Department', 'department', 'province'),
        ('DE', 4, 'county', 'County', 'county', 'department'),
        ('DE', 5, 'district', 'District', 'district', 'county'),
        ('DE', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('DJ', 1, 'region', 'Region', 'region', NULL),
        ('DK', 1, 'region', 'Region', 'region', NULL),
        ('DK', 2, 'province', 'Province', 'province', 'region'),
        ('DK', 3, 'department', 'Department', 'department', 'province'),
        ('DK', 4, 'district', 'District', 'district', 'department'),
        ('DK', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('DM', 1, 'region', 'Region', 'region', NULL),
        ('DM', 2, 'district', 'District', 'district', 'region'),
        ('DO', 1, 'region', 'Region', 'region', NULL),
        ('DO', 2, 'province', 'Province', 'province', 'region'),
        ('DO', 3, 'department', 'Department', 'department', 'province'),
        ('DO', 4, 'district', 'District', 'district', 'department'),
        ('DO', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('DZ', 1, 'region', 'Region', 'region', NULL),
        ('DZ', 2, 'province', 'Province', 'province', 'region'),
        ('DZ', 3, 'department', 'Department', 'department', 'province'),
        ('DZ', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('EC', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('EC', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('EC', 3, 'province', 'Province', 'province', 'region'),
        ('EC', 4, 'department', 'Department', 'department', 'province'),
        ('EC', 5, 'district', 'District', 'district', 'department'),
        ('EC', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('EE', 1, 'region', 'Region', 'region', NULL),
        ('EE', 2, 'department', 'Department', 'department', 'region'),
        ('EE', 3, 'county', 'County', 'county', 'department'),
        ('EE', 4, 'district', 'District', 'district', 'county'),
        ('EE', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('EG', 1, 'region', 'Region', 'region', NULL),
        ('EG', 2, 'department', 'Department', 'department', 'region'),
        ('EG', 3, 'district', 'District', 'district', 'department'),
        ('EG', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ER', 1, 'region', 'Region', 'region', NULL),
        ('ER', 2, 'province', 'Province', 'province', 'region'),
        ('ER', 3, 'department', 'Department', 'department', 'province'),
        ('ES', 1, 'region', 'Region', 'region', NULL),
        ('ES', 2, 'province', 'Province', 'province', 'region'),
        ('ES', 3, 'department', 'Department', 'department', 'province'),
        ('ES', 4, 'county', 'County', 'county', 'department'),
        ('ES', 5, 'district', 'District', 'district', 'county'),
        ('ES', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ET', 1, 'region', 'Region', 'region', NULL),
        ('ET', 2, 'province', 'Province', 'province', 'region'),
        ('ET', 3, 'department', 'Department', 'department', 'province'),
        ('ET', 4, 'district', 'District', 'district', 'department'),
        ('ET', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('FI', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('FI', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('FI', 3, 'province', 'Province', 'province', 'region'),
        ('FI', 4, 'department', 'Department', 'department', 'province'),
        ('FI', 5, 'district', 'District', 'district', 'department'),
        ('FI', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('FJ', 1, 'region', 'Region', 'region', NULL),
        ('FJ', 2, 'province', 'Province', 'province', 'region'),
        ('FJ', 3, 'department', 'Department', 'department', 'province'),
        ('FJ', 4, 'district', 'District', 'district', 'department'),
        ('FM', 1, 'region', 'Region', 'region', NULL),
        ('FM', 2, 'district', 'District', 'district', 'region'),
        ('FM', 3, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GA', 1, 'region', 'Region', 'region', NULL),
        ('GA', 2, 'province', 'Province', 'province', 'region'),
        ('GA', 3, 'municipality', 'Municipality', 'municipality', 'province'),
        ('GB', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('GB', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('GB', 3, 'province', 'Province', 'province', 'region'),
        ('GB', 4, 'department', 'Department', 'department', 'province'),
        ('GB', 5, 'county', 'County', 'county', 'department'),
        ('GB', 6, 'district', 'District', 'district', 'county'),
        ('GB', 7, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GD', 1, 'region', 'Region', 'region', NULL),
        ('GD', 2, 'department', 'Department', 'department', 'region'),
        ('GE', 1, 'region', 'Region', 'region', NULL),
        ('GE', 2, 'department', 'Department', 'department', 'region'),
        ('GE', 3, 'district', 'District', 'district', 'department'),
        ('GH', 1, 'region', 'Region', 'region', NULL),
        ('GH', 2, 'province', 'Province', 'province', 'region'),
        ('GH', 3, 'department', 'Department', 'department', 'province'),
        ('GH', 4, 'district', 'District', 'district', 'department'),
        ('GH', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GM', 1, 'region', 'Region', 'region', NULL),
        ('GM', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('GN', 1, 'region', 'Region', 'region', NULL),
        ('GN', 2, 'province', 'Province', 'province', 'region'),
        ('GN', 3, 'department', 'Department', 'department', 'province'),
        ('GN', 4, 'district', 'District', 'district', 'department'),
        ('GN', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GQ', 1, 'region', 'Region', 'region', NULL),
        ('GQ', 2, 'province', 'Province', 'province', 'region'),
        ('GQ', 3, 'district', 'District', 'district', 'province'),
        ('GQ', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GR', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('GR', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('GR', 3, 'province', 'Province', 'province', 'region'),
        ('GR', 4, 'department', 'Department', 'department', 'province'),
        ('GR', 5, 'district', 'District', 'district', 'department'),
        ('GR', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('GT', 1, 'region', 'Region', 'region', NULL),
        ('GT', 2, 'province', 'Province', 'province', 'region'),
        ('GT', 3, 'department', 'Department', 'department', 'province'),
        ('GT', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('GW', 1, 'region', 'Region', 'region', NULL),
        ('GY', 1, 'region', 'Region', 'region', NULL),
        ('GY', 2, 'province', 'Province', 'province', 'region'),
        ('GY', 3, 'department', 'Department', 'department', 'province'),
        ('HN', 1, 'region', 'Region', 'region', NULL),
        ('HN', 2, 'province', 'Province', 'province', 'region'),
        ('HN', 3, 'department', 'Department', 'department', 'province'),
        ('HN', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('HR', 1, 'region', 'Region', 'region', NULL),
        ('HR', 2, 'province', 'Province', 'province', 'region'),
        ('HR', 3, 'department', 'Department', 'department', 'province'),
        ('HR', 4, 'county', 'County', 'county', 'department'),
        ('HR', 5, 'district', 'District', 'district', 'county'),
        ('HR', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('HT', 1, 'region', 'Region', 'region', NULL),
        ('HT', 2, 'province', 'Province', 'province', 'region'),
        ('HT', 3, 'department', 'Department', 'department', 'province'),
        ('HT', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('HU', 1, 'region', 'Region', 'region', NULL),
        ('HU', 2, 'province', 'Province', 'province', 'region'),
        ('HU', 3, 'department', 'Department', 'department', 'province'),
        ('HU', 4, 'district', 'District', 'district', 'department'),
        ('HU', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ID', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('ID', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('ID', 3, 'province', 'Province', 'province', 'region'),
        ('ID', 4, 'department', 'Department', 'department', 'province'),
        ('ID', 5, 'district', 'District', 'district', 'department'),
        ('ID', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('IE', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('IE', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('IE', 3, 'province', 'Province', 'province', 'region'),
        ('IE', 4, 'department', 'Department', 'department', 'province'),
        ('IE', 5, 'county', 'County', 'county', 'department'),
        ('IE', 6, 'district', 'District', 'district', 'county'),
        ('IL', 1, 'region', 'Region', 'region', NULL),
        ('IL', 2, 'province', 'Province', 'province', 'region'),
        ('IL', 3, 'department', 'Department', 'department', 'province'),
        ('IL', 4, 'district', 'District', 'district', 'department'),
        ('IL', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('IN', 1, 'region', 'Region', 'region', NULL),
        ('IN', 2, 'province', 'Province', 'province', 'region'),
        ('IN', 3, 'department', 'Department', 'department', 'province'),
        ('IN', 4, 'district', 'District', 'district', 'department'),
        ('IN', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('IQ', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('IQ', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('IQ', 3, 'province', 'Province', 'province', 'region'),
        ('IQ', 4, 'department', 'Department', 'department', 'province'),
        ('IQ', 5, 'district', 'District', 'district', 'department'),
        ('IQ', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('IR', 1, 'region', 'Region', 'region', NULL),
        ('IR', 2, 'province', 'Province', 'province', 'region'),
        ('IR', 3, 'department', 'Department', 'department', 'province'),
        ('IR', 4, 'county', 'County', 'county', 'department'),
        ('IR', 5, 'district', 'District', 'district', 'county'),
        ('IR', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('IS', 1, 'region', 'Region', 'region', NULL),
        ('IS', 2, 'department', 'Department', 'department', 'region'),
        ('IS', 3, 'municipality', 'Municipality', 'municipality', 'department'),
        ('IT', 1, 'region', 'Region', 'region', NULL),
        ('IT', 2, 'province', 'Province', 'province', 'region'),
        ('IT', 3, 'department', 'Department', 'department', 'province'),
        ('IT', 4, 'county', 'County', 'county', 'department'),
        ('IT', 5, 'district', 'District', 'district', 'county'),
        ('IT', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('JM', 1, 'region', 'Region', 'region', NULL),
        ('JM', 2, 'province', 'Province', 'province', 'region'),
        ('JM', 3, 'department', 'Department', 'department', 'province'),
        ('JM', 4, 'county', 'County', 'county', 'department'),
        ('JO', 1, 'region', 'Region', 'region', NULL),
        ('JO', 2, 'department', 'Department', 'department', 'region'),
        ('JO', 3, 'district', 'District', 'district', 'department'),
        ('JO', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('JP', 1, 'region', 'Region', 'region', NULL),
        ('JP', 2, 'province', 'Province', 'province', 'region'),
        ('JP', 3, 'department', 'Department', 'department', 'province'),
        ('JP', 4, 'district', 'District', 'district', 'department'),
        ('JP', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('KE', 1, 'region', 'Region', 'region', NULL),
        ('KE', 2, 'province', 'Province', 'province', 'region'),
        ('KE', 3, 'department', 'Department', 'department', 'province'),
        ('KE', 4, 'county', 'County', 'county', 'department'),
        ('KE', 5, 'district', 'District', 'district', 'county'),
        ('KE', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('KG', 1, 'region', 'Region', 'region', NULL),
        ('KG', 2, 'department', 'Department', 'department', 'region'),
        ('KG', 3, 'district', 'District', 'district', 'department'),
        ('KH', 1, 'region', 'Region', 'region', NULL),
        ('KH', 2, 'province', 'Province', 'province', 'region'),
        ('KH', 3, 'department', 'Department', 'department', 'province'),
        ('KH', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('KI', 1, 'region', 'Region', 'region', NULL),
        ('KM', 1, 'region', 'Region', 'region', NULL),
        ('KM', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('KN', 1, 'region', 'Region', 'region', NULL),
        ('KN', 2, 'district', 'District', 'district', 'region'),
        ('KP', 1, 'region', 'Region', 'region', NULL),
        ('KP', 2, 'province', 'Province', 'province', 'region'),
        ('KP', 3, 'department', 'Department', 'department', 'province'),
        ('KP', 4, 'district', 'District', 'district', 'department'),
        ('KP', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('KR', 1, 'region', 'Region', 'region', NULL),
        ('KR', 2, 'province', 'Province', 'province', 'region'),
        ('KR', 3, 'department', 'Department', 'department', 'province'),
        ('KR', 4, 'county', 'County', 'county', 'department'),
        ('KR', 5, 'district', 'District', 'district', 'county'),
        ('KR', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('KW', 1, 'region', 'Region', 'region', NULL),
        ('KW', 2, 'department', 'Department', 'department', 'region'),
        ('KW', 3, 'district', 'District', 'district', 'department'),
        ('KW', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('KZ', 1, 'region', 'Region', 'region', NULL),
        ('KZ', 2, 'province', 'Province', 'province', 'region'),
        ('KZ', 3, 'department', 'Department', 'department', 'province'),
        ('KZ', 4, 'district', 'District', 'district', 'department'),
        ('LA', 1, 'region', 'Region', 'region', NULL),
        ('LB', 1, 'region', 'Region', 'region', NULL),
        ('LB', 2, 'province', 'Province', 'province', 'region'),
        ('LB', 3, 'department', 'Department', 'department', 'province'),
        ('LB', 4, 'district', 'District', 'district', 'department'),
        ('LB', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('LC', 1, 'region', 'Region', 'region', NULL),
        ('LC', 2, 'department', 'Department', 'department', 'region'),
        ('LC', 3, 'district', 'District', 'district', 'department'),
        ('LI', 1, 'region', 'Region', 'region', NULL),
        ('LI', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('LK', 1, 'region', 'Region', 'region', NULL),
        ('LK', 2, 'province', 'Province', 'province', 'region'),
        ('LK', 3, 'department', 'Department', 'department', 'province'),
        ('LK', 4, 'district', 'District', 'district', 'department'),
        ('LR', 1, 'region', 'Region', 'region', NULL),
        ('LR', 2, 'province', 'Province', 'province', 'region'),
        ('LR', 3, 'department', 'Department', 'department', 'province'),
        ('LR', 4, 'district', 'District', 'district', 'department'),
        ('LS', 1, 'region', 'Region', 'region', NULL),
        ('LS', 2, 'province', 'Province', 'province', 'region'),
        ('LS', 3, 'department', 'Department', 'department', 'province'),
        ('LT', 1, 'region', 'Region', 'region', NULL),
        ('LT', 2, 'province', 'Province', 'province', 'region'),
        ('LT', 3, 'department', 'Department', 'department', 'province'),
        ('LT', 4, 'district', 'District', 'district', 'department'),
        ('LT', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('LU', 1, 'region', 'Region', 'region', NULL),
        ('LU', 2, 'department', 'Department', 'department', 'region'),
        ('LU', 3, 'district', 'District', 'district', 'department'),
        ('LU', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('LV', 1, 'region', 'Region', 'region', NULL),
        ('LV', 2, 'province', 'Province', 'province', 'region'),
        ('LV', 3, 'department', 'Department', 'department', 'province'),
        ('LV', 4, 'county', 'County', 'county', 'department'),
        ('LV', 5, 'district', 'District', 'district', 'county'),
        ('LV', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('LY', 1, 'region', 'Region', 'region', NULL),
        ('LY', 2, 'department', 'Department', 'department', 'region'),
        ('LY', 3, 'municipality', 'Municipality', 'municipality', 'department'),
        ('MA', 1, 'region', 'Region', 'region', NULL),
        ('MA', 2, 'province', 'Province', 'province', 'region'),
        ('MA', 3, 'department', 'Department', 'department', 'province'),
        ('MA', 4, 'district', 'District', 'district', 'department'),
        ('MA', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MC', 1, 'region', 'Region', 'region', NULL),
        ('MC', 2, 'department', 'Department', 'department', 'region'),
        ('MC', 3, 'municipality', 'Municipality', 'municipality', 'department'),
        ('MD', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('MD', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('MD', 3, 'province', 'Province', 'province', 'region'),
        ('MD', 4, 'department', 'Department', 'department', 'province'),
        ('MD', 5, 'district', 'District', 'district', 'department'),
        ('MD', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ME', 1, 'region', 'Region', 'region', NULL),
        ('ME', 2, 'department', 'Department', 'department', 'region'),
        ('ME', 3, 'district', 'District', 'district', 'department'),
        ('ME', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MG', 1, 'region', 'Region', 'region', NULL),
        ('MG', 2, 'province', 'Province', 'province', 'region'),
        ('MG', 3, 'department', 'Department', 'department', 'province'),
        ('MG', 4, 'district', 'District', 'district', 'department'),
        ('MG', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MH', 1, 'region', 'Region', 'region', NULL),
        ('MK', 1, 'region', 'Region', 'region', NULL),
        ('MK', 2, 'department', 'Department', 'department', 'region'),
        ('MK', 3, 'district', 'District', 'district', 'department'),
        ('MK', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ML', 1, 'region', 'Region', 'region', NULL),
        ('ML', 2, 'province', 'Province', 'province', 'region'),
        ('ML', 3, 'department', 'Department', 'department', 'province'),
        ('ML', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('MM', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('MM', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('MM', 3, 'province', 'Province', 'province', 'region'),
        ('MM', 4, 'department', 'Department', 'department', 'province'),
        ('MM', 5, 'district', 'District', 'district', 'department'),
        ('MM', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MN', 1, 'region', 'Region', 'region', NULL),
        ('MN', 2, 'department', 'Department', 'department', 'region'),
        ('MR', 1, 'region', 'Region', 'region', NULL),
        ('MR', 2, 'department', 'Department', 'department', 'region'),
        ('MR', 3, 'district', 'District', 'district', 'department'),
        ('MR', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MT', 1, 'region', 'Region', 'region', NULL),
        ('MT', 2, 'province', 'Province', 'province', 'region'),
        ('MT', 3, 'department', 'Department', 'department', 'province'),
        ('MT', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('MU', 1, 'region', 'Region', 'region', NULL),
        ('MU', 2, 'department', 'Department', 'department', 'region'),
        ('MV', 1, 'region', 'Region', 'region', NULL),
        ('MV', 2, 'department', 'Department', 'department', 'region'),
        ('MV', 3, 'district', 'District', 'district', 'department'),
        ('MW', 1, 'region', 'Region', 'region', NULL),
        ('MW', 2, 'province', 'Province', 'province', 'region'),
        ('MW', 3, 'department', 'Department', 'department', 'province'),
        ('MW', 4, 'district', 'District', 'district', 'department'),
        ('MW', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MX', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('MX', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('MX', 3, 'province', 'Province', 'province', 'region'),
        ('MX', 4, 'department', 'Department', 'department', 'province'),
        ('MX', 5, 'district', 'District', 'district', 'department'),
        ('MX', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MY', 1, 'region', 'Region', 'region', NULL),
        ('MY', 2, 'province', 'Province', 'province', 'region'),
        ('MY', 3, 'department', 'Department', 'department', 'province'),
        ('MY', 4, 'district', 'District', 'district', 'department'),
        ('MY', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('MZ', 1, 'region', 'Region', 'region', NULL),
        ('MZ', 2, 'province', 'Province', 'province', 'region'),
        ('MZ', 3, 'department', 'Department', 'department', 'province'),
        ('MZ', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('NA', 1, 'region', 'Region', 'region', NULL),
        ('NA', 2, 'province', 'Province', 'province', 'region'),
        ('NA', 3, 'department', 'Department', 'department', 'province'),
        ('NE', 1, 'region', 'Region', 'region', NULL),
        ('NE', 2, 'province', 'Province', 'province', 'region'),
        ('NE', 3, 'department', 'Department', 'department', 'province'),
        ('NE', 4, 'district', 'District', 'district', 'department'),
        ('NE', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('NG', 1, 'region', 'Region', 'region', NULL),
        ('NG', 2, 'province', 'Province', 'province', 'region'),
        ('NG', 3, 'department', 'Department', 'department', 'province'),
        ('NG', 4, 'district', 'District', 'district', 'department'),
        ('NG', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('NI', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('NI', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('NI', 3, 'province', 'Province', 'province', 'region'),
        ('NI', 4, 'department', 'Department', 'department', 'province'),
        ('NI', 5, 'district', 'District', 'district', 'department'),
        ('NI', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('NL', 1, 'region', 'Region', 'region', NULL),
        ('NL', 2, 'department', 'Department', 'department', 'region'),
        ('NO', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('NO', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('NO', 3, 'department', 'Department', 'department', 'region'),
        ('NO', 4, 'county', 'County', 'county', 'department'),
        ('NO', 5, 'district', 'District', 'district', 'county'),
        ('NO', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('NP', 1, 'region', 'Region', 'region', NULL),
        ('NP', 2, 'province', 'Province', 'province', 'region'),
        ('NP', 3, 'department', 'Department', 'department', 'province'),
        ('NP', 4, 'district', 'District', 'district', 'department'),
        ('NP', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('NR', 1, 'region', 'Region', 'region', NULL),
        ('NR', 2, 'district', 'District', 'district', 'region'),
        ('NZ', 1, 'region', 'Region', 'region', NULL),
        ('NZ', 2, 'province', 'Province', 'province', 'region'),
        ('NZ', 3, 'department', 'Department', 'department', 'province'),
        ('NZ', 4, 'county', 'County', 'county', 'department'),
        ('NZ', 5, 'district', 'District', 'district', 'county'),
        ('NZ', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('OM', 1, 'region', 'Region', 'region', NULL),
        ('OM', 2, 'department', 'Department', 'department', 'region'),
        ('PA', 1, 'region', 'Region', 'region', NULL),
        ('PA', 2, 'province', 'Province', 'province', 'region'),
        ('PA', 3, 'department', 'Department', 'department', 'province'),
        ('PA', 4, 'district', 'District', 'district', 'department'),
        ('PE', 1, 'region', 'Region', 'region', NULL),
        ('PE', 2, 'province', 'Province', 'province', 'region'),
        ('PE', 3, 'department', 'Department', 'department', 'province'),
        ('PE', 4, 'county', 'County', 'county', 'department'),
        ('PE', 5, 'district', 'District', 'district', 'county'),
        ('PG', 1, 'region', 'Region', 'region', NULL),
        ('PG', 2, 'province', 'Province', 'province', 'region'),
        ('PG', 3, 'department', 'Department', 'department', 'province'),
        ('PG', 4, 'district', 'District', 'district', 'department'),
        ('PH', 1, 'region', 'Region', 'region', NULL),
        ('PH', 2, 'province', 'Province', 'province', 'region'),
        ('PH', 3, 'department', 'Department', 'department', 'province'),
        ('PH', 4, 'district', 'District', 'district', 'department'),
        ('PH', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('PK', 1, 'region', 'Region', 'region', NULL),
        ('PK', 2, 'province', 'Province', 'province', 'region'),
        ('PK', 3, 'department', 'Department', 'department', 'province'),
        ('PK', 4, 'district', 'District', 'district', 'department'),
        ('PK', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('PL', 1, 'region', 'Region', 'region', NULL),
        ('PL', 2, 'province', 'Province', 'province', 'region'),
        ('PL', 3, 'department', 'Department', 'department', 'province'),
        ('PL', 4, 'county', 'County', 'county', 'department'),
        ('PL', 5, 'district', 'District', 'district', 'county'),
        ('PL', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('PS', 1, 'region', 'Region', 'region', NULL),
        ('PS', 2, 'department', 'Department', 'department', 'region'),
        ('PS', 3, 'district', 'District', 'district', 'department'),
        ('PS', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('PT', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('PT', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('PT', 3, 'province', 'Province', 'province', 'region'),
        ('PT', 4, 'department', 'Department', 'department', 'province'),
        ('PT', 5, 'county', 'County', 'county', 'department'),
        ('PT', 6, 'district', 'District', 'district', 'county'),
        ('PT', 7, 'municipality', 'Municipality', 'municipality', 'district'),
        ('PW', 1, 'region', 'Region', 'region', NULL),
        ('PW', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('PY', 1, 'region', 'Region', 'region', NULL),
        ('PY', 2, 'province', 'Province', 'province', 'region'),
        ('PY', 3, 'department', 'Department', 'department', 'province'),
        ('PY', 4, 'district', 'District', 'district', 'department'),
        ('PY', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('QA', 1, 'region', 'Region', 'region', NULL),
        ('QA', 2, 'department', 'Department', 'department', 'region'),
        ('QA', 3, 'district', 'District', 'district', 'department'),
        ('QA', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('RO', 1, 'region', 'Region', 'region', NULL),
        ('RO', 2, 'province', 'Province', 'province', 'region'),
        ('RO', 3, 'department', 'Department', 'department', 'province'),
        ('RO', 4, 'district', 'District', 'district', 'department'),
        ('RO', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('RS', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('RS', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('RS', 3, 'province', 'Province', 'province', 'region'),
        ('RS', 4, 'department', 'Department', 'department', 'province'),
        ('RS', 5, 'district', 'District', 'district', 'department'),
        ('RS', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('RU', 1, 'region', 'Region', 'region', NULL),
        ('RU', 2, 'province', 'Province', 'province', 'region'),
        ('RU', 3, 'department', 'Department', 'department', 'province'),
        ('RU', 4, 'district', 'District', 'district', 'department'),
        ('RU', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('RW', 1, 'region', 'Region', 'region', NULL),
        ('RW', 2, 'province', 'Province', 'province', 'region'),
        ('RW', 3, 'department', 'Department', 'department', 'province'),
        ('RW', 4, 'district', 'District', 'district', 'department'),
        ('RW', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SA', 1, 'region', 'Region', 'region', NULL),
        ('SA', 2, 'province', 'Province', 'province', 'region'),
        ('SA', 3, 'department', 'Department', 'department', 'province'),
        ('SA', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('SB', 1, 'region', 'Region', 'region', NULL),
        ('SB', 2, 'province', 'Province', 'province', 'region'),
        ('SB', 3, 'department', 'Department', 'department', 'province'),
        ('SB', 4, 'district', 'District', 'district', 'department'),
        ('SC', 1, 'region', 'Region', 'region', NULL),
        ('SD', 1, 'region', 'Region', 'region', NULL),
        ('SD', 2, 'province', 'Province', 'province', 'region'),
        ('SD', 3, 'department', 'Department', 'department', 'province'),
        ('SD', 4, 'district', 'District', 'district', 'department'),
        ('SE', 1, 'region', 'Region', 'region', NULL),
        ('SE', 2, 'province', 'Province', 'province', 'region'),
        ('SE', 3, 'department', 'Department', 'department', 'province'),
        ('SE', 4, 'district', 'District', 'district', 'department'),
        ('SE', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SG', 1, 'region', 'Region', 'region', NULL),
        ('SG', 2, 'department', 'Department', 'department', 'region'),
        ('SG', 3, 'district', 'District', 'district', 'department'),
        ('SI', 1, 'region', 'Region', 'region', NULL),
        ('SI', 2, 'province', 'Province', 'province', 'region'),
        ('SI', 3, 'department', 'Department', 'department', 'province'),
        ('SI', 4, 'district', 'District', 'district', 'department'),
        ('SI', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SK', 1, 'region', 'Region', 'region', NULL),
        ('SK', 2, 'province', 'Province', 'province', 'region'),
        ('SK', 3, 'department', 'Department', 'department', 'province'),
        ('SK', 4, 'district', 'District', 'district', 'department'),
        ('SK', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SL', 1, 'region', 'Region', 'region', NULL),
        ('SL', 2, 'province', 'Province', 'province', 'region'),
        ('SL', 3, 'district', 'District', 'district', 'province'),
        ('SL', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SM', 1, 'region', 'Region', 'region', NULL),
        ('SM', 2, 'department', 'Department', 'department', 'region'),
        ('SN', 1, 'region', 'Region', 'region', NULL),
        ('SN', 2, 'province', 'Province', 'province', 'region'),
        ('SN', 3, 'department', 'Department', 'department', 'province'),
        ('SN', 4, 'district', 'District', 'district', 'department'),
        ('SN', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SO', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('SO', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('SO', 3, 'district', 'District', 'district', 'region'),
        ('SR', 1, 'region', 'Region', 'region', NULL),
        ('SR', 2, 'department', 'Department', 'department', 'region'),
        ('SR', 3, 'district', 'District', 'district', 'department'),
        ('SS', 1, 'region', 'Region', 'region', NULL),
        ('SS', 2, 'province', 'Province', 'province', 'region'),
        ('ST', 1, 'region', 'Region', 'region', NULL),
        ('ST', 2, 'municipality', 'Municipality', 'municipality', 'region'),
        ('SV', 1, 'region', 'Region', 'region', NULL),
        ('SV', 2, 'province', 'Province', 'province', 'region'),
        ('SV', 3, 'department', 'Department', 'department', 'province'),
        ('SV', 4, 'district', 'District', 'district', 'department'),
        ('SV', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SY', 1, 'autonomous_region', 'Autonomous Region', 'autonomous_region', NULL),
        ('SY', 2, 'region', 'Region', 'region', 'autonomous_region'),
        ('SY', 3, 'province', 'Province', 'province', 'region'),
        ('SY', 4, 'department', 'Department', 'department', 'province'),
        ('SY', 5, 'district', 'District', 'district', 'department'),
        ('SY', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('SZ', 1, 'region', 'Region', 'region', NULL),
        ('SZ', 2, 'department', 'Department', 'department', 'region'),
        ('TD', 1, 'region', 'Region', 'region', NULL),
        ('TD', 2, 'province', 'Province', 'province', 'region'),
        ('TD', 3, 'department', 'Department', 'department', 'province'),
        ('TD', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('TG', 1, 'region', 'Region', 'region', NULL),
        ('TG', 2, 'province', 'Province', 'province', 'region'),
        ('TG', 3, 'department', 'Department', 'department', 'province'),
        ('TG', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('TH', 1, 'region', 'Region', 'region', NULL),
        ('TH', 2, 'province', 'Province', 'province', 'region'),
        ('TH', 3, 'department', 'Department', 'department', 'province'),
        ('TH', 4, 'district', 'District', 'district', 'department'),
        ('TH', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('TJ', 1, 'region', 'Region', 'region', NULL),
        ('TJ', 2, 'department', 'Department', 'department', 'region'),
        ('TJ', 3, 'district', 'District', 'district', 'department'),
        ('TL', 1, 'region', 'Region', 'region', NULL),
        ('TL', 2, 'department', 'Department', 'department', 'region'),
        ('TM', 1, 'region', 'Region', 'region', NULL),
        ('TM', 2, 'department', 'Department', 'department', 'region'),
        ('TM', 3, 'district', 'District', 'district', 'department'),
        ('TN', 1, 'region', 'Region', 'region', NULL),
        ('TN', 2, 'department', 'Department', 'department', 'region'),
        ('TN', 3, 'district', 'District', 'district', 'department'),
        ('TN', 4, 'municipality', 'Municipality', 'municipality', 'district'),
        ('TO', 1, 'region', 'Region', 'region', NULL),
        ('TO', 2, 'department', 'Department', 'department', 'region'),
        ('TO', 3, 'district', 'District', 'district', 'department'),
        ('TR', 1, 'region', 'Region', 'region', NULL),
        ('TR', 2, 'province', 'Province', 'province', 'region'),
        ('TR', 3, 'department', 'Department', 'department', 'province'),
        ('TR', 4, 'district', 'District', 'district', 'department'),
        ('TR', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('TT', 1, 'region', 'Region', 'region', NULL),
        ('TT', 2, 'province', 'Province', 'province', 'region'),
        ('TT', 3, 'department', 'Department', 'department', 'province'),
        ('TV', 1, 'region', 'Region', 'region', NULL),
        ('TW', 1, 'region', 'Region', 'region', NULL),
        ('TW', 2, 'province', 'Province', 'province', 'region'),
        ('TW', 3, 'department', 'Department', 'department', 'province'),
        ('TW', 4, 'county', 'County', 'county', 'department'),
        ('TW', 5, 'district', 'District', 'district', 'county'),
        ('TW', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('TZ', 1, 'region', 'Region', 'region', NULL),
        ('TZ', 2, 'province', 'Province', 'province', 'region'),
        ('TZ', 3, 'department', 'Department', 'department', 'province'),
        ('TZ', 4, 'district', 'District', 'district', 'department'),
        ('TZ', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('UA', 1, 'region', 'Region', 'region', NULL),
        ('UA', 2, 'province', 'Province', 'province', 'region'),
        ('UA', 3, 'department', 'Department', 'department', 'province'),
        ('UA', 4, 'district', 'District', 'district', 'department'),
        ('UA', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('UG', 1, 'region', 'Region', 'region', NULL),
        ('UG', 2, 'province', 'Province', 'province', 'region'),
        ('UG', 3, 'department', 'Department', 'department', 'province'),
        ('UG', 4, 'county', 'County', 'county', 'department'),
        ('UG', 5, 'district', 'District', 'district', 'county'),
        ('UG', 6, 'municipality', 'Municipality', 'municipality', 'district'),
        ('US', 1, 'overseas_region', 'Overseas Region', 'overseas_region', NULL),
        ('US', 2, 'region', 'Region', 'region', 'overseas_region'),
        ('US', 3, 'province', 'Province', 'province', 'region'),
        ('US', 4, 'department', 'Department', 'department', 'province'),
        ('US', 5, 'county', 'County', 'county', 'department'),
        ('US', 6, 'district', 'District', 'district', 'county'),
        ('US', 7, 'municipality', 'Municipality', 'municipality', 'district'),
        ('UY', 1, 'region', 'Region', 'region', NULL),
        ('UY', 2, 'province', 'Province', 'province', 'region'),
        ('UY', 3, 'department', 'Department', 'department', 'province'),
        ('UY', 4, 'municipality', 'Municipality', 'municipality', 'department'),
        ('UZ', 1, 'region', 'Region', 'region', NULL),
        ('UZ', 2, 'province', 'Province', 'province', 'region'),
        ('UZ', 3, 'department', 'Department', 'department', 'province'),
        ('UZ', 4, 'district', 'District', 'district', 'department'),
        ('VA', 1, 'region', 'Region', 'region', NULL),
        ('VA', 2, 'department', 'Department', 'department', 'region'),
        ('VC', 1, 'region', 'Region', 'region', NULL),
        ('VE', 1, 'region', 'Region', 'region', NULL),
        ('VE', 2, 'province', 'Province', 'province', 'region'),
        ('VE', 3, 'department', 'Department', 'department', 'province'),
        ('VE', 4, 'district', 'District', 'district', 'department'),
        ('VE', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('VN', 1, 'region', 'Region', 'region', NULL),
        ('VN', 2, 'province', 'Province', 'province', 'region'),
        ('VN', 3, 'department', 'Department', 'department', 'province'),
        ('VN', 4, 'district', 'District', 'district', 'department'),
        ('VN', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('VU', 1, 'region', 'Region', 'region', NULL),
        ('VU', 2, 'province', 'Province', 'province', 'region'),
        ('VU', 3, 'department', 'Department', 'department', 'province'),
        ('WS', 1, 'region', 'Region', 'region', NULL),
        ('WS', 2, 'province', 'Province', 'province', 'region'),
        ('XK', 1, 'region', 'Region', 'region', NULL),
        ('XK', 2, 'department', 'Department', 'department', 'region'),
        ('YE', 1, 'region', 'Region', 'region', NULL),
        ('YE', 2, 'province', 'Province', 'province', 'region'),
        ('YE', 3, 'department', 'Department', 'department', 'province'),
        ('YE', 4, 'district', 'District', 'district', 'department'),
        ('ZA', 1, 'region', 'Region', 'region', NULL),
        ('ZA', 2, 'province', 'Province', 'province', 'region'),
        ('ZA', 3, 'department', 'Department', 'department', 'province'),
        ('ZA', 4, 'district', 'District', 'district', 'department'),
        ('ZA', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ZM', 1, 'region', 'Region', 'region', NULL),
        ('ZM', 2, 'province', 'Province', 'province', 'region'),
        ('ZM', 3, 'department', 'Department', 'department', 'province'),
        ('ZM', 4, 'district', 'District', 'district', 'department'),
        ('ZM', 5, 'municipality', 'Municipality', 'municipality', 'district'),
        ('ZW', 1, 'region', 'Region', 'region', NULL),
        ('ZW', 2, 'province', 'Province', 'province', 'region'),
        ('ZW', 3, 'department', 'Department', 'department', 'province'),
        ('ZW', 4, 'district', 'District', 'district', 'department')
),
country_seed AS (
    SELECT
        c.id AS country_id,
        s.level_number,
        s.code,
        s.label,
        s.default_territory_type_code
    FROM seed s
    JOIN country c ON c.iso_code = s.country_iso
)
INSERT INTO country_admin_level (
    country_id,
    level_number,
    code,
    label,
    default_territory_type_code,
    parent_level_id,
    is_current
)
SELECT
    cs.country_id,
    cs.level_number,
    cs.code,
    cs.label,
    cs.default_territory_type_code,
    NULL,
    TRUE
FROM country_seed cs
ON CONFLICT (country_id, code) DO UPDATE
SET
    level_number = EXCLUDED.level_number,
    label = EXCLUDED.label,
    default_territory_type_code = EXCLUDED.default_territory_type_code,
    parent_level_id = NULL,
    is_current = EXCLUDED.is_current;

WITH parent_seed(country_iso, child_code, parent_code) AS (
    VALUES
        ('AD', 'province', 'region'),
        ('AD', 'department', 'province'),
        ('AD', 'municipality', 'department'),
        ('AE', 'province', 'region'),
        ('AE', 'department', 'province'),
        ('AE', 'district', 'department'),
        ('AF', 'department', 'region'),
        ('AF', 'district', 'department'),
        ('AG', 'department', 'region'),
        ('AL', 'province', 'region'),
        ('AL', 'department', 'province'),
        ('AL', 'municipality', 'department'),
        ('AM', 'department', 'region'),
        ('AM', 'district', 'department'),
        ('AM', 'municipality', 'district'),
        ('AO', 'province', 'region'),
        ('AO', 'department', 'province'),
        ('AO', 'district', 'department'),
        ('AO', 'municipality', 'district'),
        ('AR', 'province', 'region'),
        ('AR', 'department', 'province'),
        ('AR', 'district', 'department'),
        ('AR', 'municipality', 'district'),
        ('AT', 'province', 'region'),
        ('AT', 'department', 'province'),
        ('AT', 'district', 'department'),
        ('AT', 'municipality', 'district'),
        ('AU', 'region', 'overseas_region'),
        ('AU', 'province', 'region'),
        ('AU', 'department', 'province'),
        ('AU', 'county', 'department'),
        ('AU', 'district', 'county'),
        ('AU', 'municipality', 'district'),
        ('AZ', 'department', 'region'),
        ('AZ', 'district', 'department'),
        ('AZ', 'municipality', 'district'),
        ('BA', 'province', 'region'),
        ('BA', 'department', 'province'),
        ('BA', 'district', 'department'),
        ('BA', 'municipality', 'district'),
        ('BB', 'department', 'region'),
        ('BD', 'province', 'region'),
        ('BD', 'department', 'province'),
        ('BD', 'district', 'department'),
        ('BD', 'municipality', 'district'),
        ('BE', 'province', 'region'),
        ('BE', 'department', 'province'),
        ('BE', 'district', 'department'),
        ('BE', 'municipality', 'district'),
        ('BF', 'province', 'region'),
        ('BF', 'department', 'province'),
        ('BF', 'district', 'department'),
        ('BF', 'municipality', 'district'),
        ('BG', 'province', 'region'),
        ('BG', 'department', 'province'),
        ('BG', 'district', 'department'),
        ('BG', 'municipality', 'district'),
        ('BH', 'department', 'region'),
        ('BH', 'district', 'department'),
        ('BI', 'province', 'region'),
        ('BI', 'district', 'province'),
        ('BI', 'municipality', 'district'),
        ('BJ', 'province', 'region'),
        ('BJ', 'department', 'province'),
        ('BJ', 'district', 'department'),
        ('BJ', 'municipality', 'district'),
        ('BN', 'department', 'region'),
        ('BN', 'municipality', 'department'),
        ('BO', 'province', 'region'),
        ('BO', 'department', 'province'),
        ('BO', 'district', 'department'),
        ('BO', 'municipality', 'district'),
        ('BR', 'province', 'region'),
        ('BR', 'department', 'province'),
        ('BR', 'district', 'department'),
        ('BR', 'municipality', 'district'),
        ('BS', 'province', 'region'),
        ('BS', 'department', 'province'),
        ('BS', 'district', 'department'),
        ('BS', 'municipality', 'district'),
        ('BT', 'department', 'region'),
        ('BT', 'district', 'department'),
        ('BW', 'department', 'region'),
        ('BY', 'province', 'region'),
        ('BY', 'department', 'province'),
        ('BY', 'district', 'department'),
        ('BZ', 'department', 'region'),
        ('BZ', 'district', 'department'),
        ('BZ', 'municipality', 'district'),
        ('CA', 'region', 'autonomous_region'),
        ('CA', 'province', 'region'),
        ('CA', 'department', 'province'),
        ('CA', 'county', 'department'),
        ('CA', 'district', 'county'),
        ('CA', 'municipality', 'district'),
        ('CD', 'province', 'region'),
        ('CD', 'department', 'province'),
        ('CD', 'district', 'department'),
        ('CD', 'municipality', 'district'),
        ('CF', 'province', 'region'),
        ('CF', 'district', 'province'),
        ('CF', 'municipality', 'district'),
        ('CG', 'province', 'region'),
        ('CG', 'department', 'province'),
        ('CG', 'district', 'department'),
        ('CG', 'municipality', 'district'),
        ('CH', 'province', 'region'),
        ('CH', 'department', 'province'),
        ('CH', 'district', 'department'),
        ('CH', 'municipality', 'district'),
        ('CL', 'region', 'overseas_region'),
        ('CL', 'province', 'region'),
        ('CL', 'department', 'province'),
        ('CL', 'district', 'department'),
        ('CL', 'municipality', 'district'),
        ('CM', 'province', 'region'),
        ('CM', 'department', 'province'),
        ('CM', 'district', 'department'),
        ('CM', 'municipality', 'district'),
        ('CN', 'province', 'region'),
        ('CN', 'department', 'province'),
        ('CN', 'county', 'department'),
        ('CN', 'district', 'county'),
        ('CN', 'municipality', 'district'),
        ('CO', 'province', 'region'),
        ('CO', 'department', 'province'),
        ('CO', 'district', 'department'),
        ('CO', 'municipality', 'district'),
        ('CR', 'province', 'region'),
        ('CR', 'district', 'province'),
        ('CR', 'municipality', 'district'),
        ('CU', 'province', 'region'),
        ('CU', 'department', 'province'),
        ('CU', 'district', 'department'),
        ('CU', 'municipality', 'district'),
        ('CV', 'municipality', 'region'),
        ('CY', 'region', 'autonomous_region'),
        ('CY', 'province', 'region'),
        ('CY', 'department', 'province'),
        ('CY', 'district', 'department'),
        ('CY', 'municipality', 'district'),
        ('CZ', 'province', 'region'),
        ('CZ', 'department', 'province'),
        ('CZ', 'district', 'department'),
        ('CZ', 'municipality', 'district'),
        ('DE', 'province', 'region'),
        ('DE', 'department', 'province'),
        ('DE', 'county', 'department'),
        ('DE', 'district', 'county'),
        ('DE', 'municipality', 'district'),
        ('DK', 'province', 'region'),
        ('DK', 'department', 'province'),
        ('DK', 'district', 'department'),
        ('DK', 'municipality', 'district'),
        ('DM', 'district', 'region'),
        ('DO', 'province', 'region'),
        ('DO', 'department', 'province'),
        ('DO', 'district', 'department'),
        ('DO', 'municipality', 'district'),
        ('DZ', 'province', 'region'),
        ('DZ', 'department', 'province'),
        ('DZ', 'municipality', 'department'),
        ('EC', 'region', 'overseas_region'),
        ('EC', 'province', 'region'),
        ('EC', 'department', 'province'),
        ('EC', 'district', 'department'),
        ('EC', 'municipality', 'district'),
        ('EE', 'department', 'region'),
        ('EE', 'county', 'department'),
        ('EE', 'district', 'county'),
        ('EE', 'municipality', 'district'),
        ('EG', 'department', 'region'),
        ('EG', 'district', 'department'),
        ('EG', 'municipality', 'district'),
        ('ER', 'province', 'region'),
        ('ER', 'department', 'province'),
        ('ES', 'province', 'region'),
        ('ES', 'department', 'province'),
        ('ES', 'county', 'department'),
        ('ES', 'district', 'county'),
        ('ES', 'municipality', 'district'),
        ('ET', 'province', 'region'),
        ('ET', 'department', 'province'),
        ('ET', 'district', 'department'),
        ('ET', 'municipality', 'district'),
        ('FI', 'region', 'autonomous_region'),
        ('FI', 'province', 'region'),
        ('FI', 'department', 'province'),
        ('FI', 'district', 'department'),
        ('FI', 'municipality', 'district'),
        ('FJ', 'province', 'region'),
        ('FJ', 'department', 'province'),
        ('FJ', 'district', 'department'),
        ('FM', 'district', 'region'),
        ('FM', 'municipality', 'district'),
        ('GA', 'province', 'region'),
        ('GA', 'municipality', 'province'),
        ('GB', 'region', 'overseas_region'),
        ('GB', 'province', 'region'),
        ('GB', 'department', 'province'),
        ('GB', 'county', 'department'),
        ('GB', 'district', 'county'),
        ('GB', 'municipality', 'district'),
        ('GD', 'department', 'region'),
        ('GE', 'department', 'region'),
        ('GE', 'district', 'department'),
        ('GH', 'province', 'region'),
        ('GH', 'department', 'province'),
        ('GH', 'district', 'department'),
        ('GH', 'municipality', 'district'),
        ('GM', 'municipality', 'region'),
        ('GN', 'province', 'region'),
        ('GN', 'department', 'province'),
        ('GN', 'district', 'department'),
        ('GN', 'municipality', 'district'),
        ('GQ', 'province', 'region'),
        ('GQ', 'district', 'province'),
        ('GQ', 'municipality', 'district'),
        ('GR', 'region', 'autonomous_region'),
        ('GR', 'province', 'region'),
        ('GR', 'department', 'province'),
        ('GR', 'district', 'department'),
        ('GR', 'municipality', 'district'),
        ('GT', 'province', 'region'),
        ('GT', 'department', 'province'),
        ('GT', 'municipality', 'department'),
        ('GY', 'province', 'region'),
        ('GY', 'department', 'province'),
        ('HN', 'province', 'region'),
        ('HN', 'department', 'province'),
        ('HN', 'municipality', 'department'),
        ('HR', 'province', 'region'),
        ('HR', 'department', 'province'),
        ('HR', 'county', 'department'),
        ('HR', 'district', 'county'),
        ('HR', 'municipality', 'district'),
        ('HT', 'province', 'region'),
        ('HT', 'department', 'province'),
        ('HT', 'municipality', 'department'),
        ('HU', 'province', 'region'),
        ('HU', 'department', 'province'),
        ('HU', 'district', 'department'),
        ('HU', 'municipality', 'district'),
        ('ID', 'region', 'autonomous_region'),
        ('ID', 'province', 'region'),
        ('ID', 'department', 'province'),
        ('ID', 'district', 'department'),
        ('ID', 'municipality', 'district'),
        ('IE', 'region', 'autonomous_region'),
        ('IE', 'province', 'region'),
        ('IE', 'department', 'province'),
        ('IE', 'county', 'department'),
        ('IE', 'district', 'county'),
        ('IL', 'province', 'region'),
        ('IL', 'department', 'province'),
        ('IL', 'district', 'department'),
        ('IL', 'municipality', 'district'),
        ('IN', 'province', 'region'),
        ('IN', 'department', 'province'),
        ('IN', 'district', 'department'),
        ('IN', 'municipality', 'district'),
        ('IQ', 'region', 'autonomous_region'),
        ('IQ', 'province', 'region'),
        ('IQ', 'department', 'province'),
        ('IQ', 'district', 'department'),
        ('IQ', 'municipality', 'district'),
        ('IR', 'province', 'region'),
        ('IR', 'department', 'province'),
        ('IR', 'county', 'department'),
        ('IR', 'district', 'county'),
        ('IR', 'municipality', 'district'),
        ('IS', 'department', 'region'),
        ('IS', 'municipality', 'department'),
        ('IT', 'province', 'region'),
        ('IT', 'department', 'province'),
        ('IT', 'county', 'department'),
        ('IT', 'district', 'county'),
        ('IT', 'municipality', 'district'),
        ('JM', 'province', 'region'),
        ('JM', 'department', 'province'),
        ('JM', 'county', 'department'),
        ('JO', 'department', 'region'),
        ('JO', 'district', 'department'),
        ('JO', 'municipality', 'district'),
        ('JP', 'province', 'region'),
        ('JP', 'department', 'province'),
        ('JP', 'district', 'department'),
        ('JP', 'municipality', 'district'),
        ('KE', 'province', 'region'),
        ('KE', 'department', 'province'),
        ('KE', 'county', 'department'),
        ('KE', 'district', 'county'),
        ('KE', 'municipality', 'district'),
        ('KG', 'department', 'region'),
        ('KG', 'district', 'department'),
        ('KH', 'province', 'region'),
        ('KH', 'department', 'province'),
        ('KH', 'municipality', 'department'),
        ('KM', 'municipality', 'region'),
        ('KN', 'district', 'region'),
        ('KP', 'province', 'region'),
        ('KP', 'department', 'province'),
        ('KP', 'district', 'department'),
        ('KP', 'municipality', 'district'),
        ('KR', 'province', 'region'),
        ('KR', 'department', 'province'),
        ('KR', 'county', 'department'),
        ('KR', 'district', 'county'),
        ('KR', 'municipality', 'district'),
        ('KW', 'department', 'region'),
        ('KW', 'district', 'department'),
        ('KW', 'municipality', 'district'),
        ('KZ', 'province', 'region'),
        ('KZ', 'department', 'province'),
        ('KZ', 'district', 'department'),
        ('LB', 'province', 'region'),
        ('LB', 'department', 'province'),
        ('LB', 'district', 'department'),
        ('LB', 'municipality', 'district'),
        ('LC', 'department', 'region'),
        ('LC', 'district', 'department'),
        ('LI', 'municipality', 'region'),
        ('LK', 'province', 'region'),
        ('LK', 'department', 'province'),
        ('LK', 'district', 'department'),
        ('LR', 'province', 'region'),
        ('LR', 'department', 'province'),
        ('LR', 'district', 'department'),
        ('LS', 'province', 'region'),
        ('LS', 'department', 'province'),
        ('LT', 'province', 'region'),
        ('LT', 'department', 'province'),
        ('LT', 'district', 'department'),
        ('LT', 'municipality', 'district'),
        ('LU', 'department', 'region'),
        ('LU', 'district', 'department'),
        ('LU', 'municipality', 'district'),
        ('LV', 'province', 'region'),
        ('LV', 'department', 'province'),
        ('LV', 'county', 'department'),
        ('LV', 'district', 'county'),
        ('LV', 'municipality', 'district'),
        ('LY', 'department', 'region'),
        ('LY', 'municipality', 'department'),
        ('MA', 'province', 'region'),
        ('MA', 'department', 'province'),
        ('MA', 'district', 'department'),
        ('MA', 'municipality', 'district'),
        ('MC', 'department', 'region'),
        ('MC', 'municipality', 'department'),
        ('MD', 'region', 'autonomous_region'),
        ('MD', 'province', 'region'),
        ('MD', 'department', 'province'),
        ('MD', 'district', 'department'),
        ('MD', 'municipality', 'district'),
        ('ME', 'department', 'region'),
        ('ME', 'district', 'department'),
        ('ME', 'municipality', 'district'),
        ('MG', 'province', 'region'),
        ('MG', 'department', 'province'),
        ('MG', 'district', 'department'),
        ('MG', 'municipality', 'district'),
        ('MK', 'department', 'region'),
        ('MK', 'district', 'department'),
        ('MK', 'municipality', 'district'),
        ('ML', 'province', 'region'),
        ('ML', 'department', 'province'),
        ('ML', 'municipality', 'department'),
        ('MM', 'region', 'autonomous_region'),
        ('MM', 'province', 'region'),
        ('MM', 'department', 'province'),
        ('MM', 'district', 'department'),
        ('MM', 'municipality', 'district'),
        ('MN', 'department', 'region'),
        ('MR', 'department', 'region'),
        ('MR', 'district', 'department'),
        ('MR', 'municipality', 'district'),
        ('MT', 'province', 'region'),
        ('MT', 'department', 'province'),
        ('MT', 'municipality', 'department'),
        ('MU', 'department', 'region'),
        ('MV', 'department', 'region'),
        ('MV', 'district', 'department'),
        ('MW', 'province', 'region'),
        ('MW', 'department', 'province'),
        ('MW', 'district', 'department'),
        ('MW', 'municipality', 'district'),
        ('MX', 'region', 'autonomous_region'),
        ('MX', 'province', 'region'),
        ('MX', 'department', 'province'),
        ('MX', 'district', 'department'),
        ('MX', 'municipality', 'district'),
        ('MY', 'province', 'region'),
        ('MY', 'department', 'province'),
        ('MY', 'district', 'department'),
        ('MY', 'municipality', 'district'),
        ('MZ', 'province', 'region'),
        ('MZ', 'department', 'province'),
        ('MZ', 'municipality', 'department'),
        ('NA', 'province', 'region'),
        ('NA', 'department', 'province'),
        ('NE', 'province', 'region'),
        ('NE', 'department', 'province'),
        ('NE', 'district', 'department'),
        ('NE', 'municipality', 'district'),
        ('NG', 'province', 'region'),
        ('NG', 'department', 'province'),
        ('NG', 'district', 'department'),
        ('NG', 'municipality', 'district'),
        ('NI', 'region', 'autonomous_region'),
        ('NI', 'province', 'region'),
        ('NI', 'department', 'province'),
        ('NI', 'district', 'department'),
        ('NI', 'municipality', 'district'),
        ('NL', 'department', 'region'),
        ('NO', 'region', 'overseas_region'),
        ('NO', 'department', 'region'),
        ('NO', 'county', 'department'),
        ('NO', 'district', 'county'),
        ('NO', 'municipality', 'district'),
        ('NP', 'province', 'region'),
        ('NP', 'department', 'province'),
        ('NP', 'district', 'department'),
        ('NP', 'municipality', 'district'),
        ('NR', 'district', 'region'),
        ('NZ', 'province', 'region'),
        ('NZ', 'department', 'province'),
        ('NZ', 'county', 'department'),
        ('NZ', 'district', 'county'),
        ('NZ', 'municipality', 'district'),
        ('OM', 'department', 'region'),
        ('PA', 'province', 'region'),
        ('PA', 'department', 'province'),
        ('PA', 'district', 'department'),
        ('PE', 'province', 'region'),
        ('PE', 'department', 'province'),
        ('PE', 'county', 'department'),
        ('PE', 'district', 'county'),
        ('PG', 'province', 'region'),
        ('PG', 'department', 'province'),
        ('PG', 'district', 'department'),
        ('PH', 'province', 'region'),
        ('PH', 'department', 'province'),
        ('PH', 'district', 'department'),
        ('PH', 'municipality', 'district'),
        ('PK', 'province', 'region'),
        ('PK', 'department', 'province'),
        ('PK', 'district', 'department'),
        ('PK', 'municipality', 'district'),
        ('PL', 'province', 'region'),
        ('PL', 'department', 'province'),
        ('PL', 'county', 'department'),
        ('PL', 'district', 'county'),
        ('PL', 'municipality', 'district'),
        ('PS', 'department', 'region'),
        ('PS', 'district', 'department'),
        ('PS', 'municipality', 'district'),
        ('PT', 'region', 'overseas_region'),
        ('PT', 'province', 'region'),
        ('PT', 'department', 'province'),
        ('PT', 'county', 'department'),
        ('PT', 'district', 'county'),
        ('PT', 'municipality', 'district'),
        ('PW', 'municipality', 'region'),
        ('PY', 'province', 'region'),
        ('PY', 'department', 'province'),
        ('PY', 'district', 'department'),
        ('PY', 'municipality', 'district'),
        ('QA', 'department', 'region'),
        ('QA', 'district', 'department'),
        ('QA', 'municipality', 'district'),
        ('RO', 'province', 'region'),
        ('RO', 'department', 'province'),
        ('RO', 'district', 'department'),
        ('RO', 'municipality', 'district'),
        ('RS', 'region', 'autonomous_region'),
        ('RS', 'province', 'region'),
        ('RS', 'department', 'province'),
        ('RS', 'district', 'department'),
        ('RS', 'municipality', 'district'),
        ('RU', 'province', 'region'),
        ('RU', 'department', 'province'),
        ('RU', 'district', 'department'),
        ('RU', 'municipality', 'district'),
        ('RW', 'province', 'region'),
        ('RW', 'department', 'province'),
        ('RW', 'district', 'department'),
        ('RW', 'municipality', 'district'),
        ('SA', 'province', 'region'),
        ('SA', 'department', 'province'),
        ('SA', 'municipality', 'department'),
        ('SB', 'province', 'region'),
        ('SB', 'department', 'province'),
        ('SB', 'district', 'department'),
        ('SD', 'province', 'region'),
        ('SD', 'department', 'province'),
        ('SD', 'district', 'department'),
        ('SE', 'province', 'region'),
        ('SE', 'department', 'province'),
        ('SE', 'district', 'department'),
        ('SE', 'municipality', 'district'),
        ('SG', 'department', 'region'),
        ('SG', 'district', 'department'),
        ('SI', 'province', 'region'),
        ('SI', 'department', 'province'),
        ('SI', 'district', 'department'),
        ('SI', 'municipality', 'district'),
        ('SK', 'province', 'region'),
        ('SK', 'department', 'province'),
        ('SK', 'district', 'department'),
        ('SK', 'municipality', 'district'),
        ('SL', 'province', 'region'),
        ('SL', 'district', 'province'),
        ('SL', 'municipality', 'district'),
        ('SM', 'department', 'region'),
        ('SN', 'province', 'region'),
        ('SN', 'department', 'province'),
        ('SN', 'district', 'department'),
        ('SN', 'municipality', 'district'),
        ('SO', 'region', 'autonomous_region'),
        ('SO', 'district', 'region'),
        ('SR', 'department', 'region'),
        ('SR', 'district', 'department'),
        ('SS', 'province', 'region'),
        ('ST', 'municipality', 'region'),
        ('SV', 'province', 'region'),
        ('SV', 'department', 'province'),
        ('SV', 'district', 'department'),
        ('SV', 'municipality', 'district'),
        ('SY', 'region', 'autonomous_region'),
        ('SY', 'province', 'region'),
        ('SY', 'department', 'province'),
        ('SY', 'district', 'department'),
        ('SY', 'municipality', 'district'),
        ('SZ', 'department', 'region'),
        ('TD', 'province', 'region'),
        ('TD', 'department', 'province'),
        ('TD', 'municipality', 'department'),
        ('TG', 'province', 'region'),
        ('TG', 'department', 'province'),
        ('TG', 'municipality', 'department'),
        ('TH', 'province', 'region'),
        ('TH', 'department', 'province'),
        ('TH', 'district', 'department'),
        ('TH', 'municipality', 'district'),
        ('TJ', 'department', 'region'),
        ('TJ', 'district', 'department'),
        ('TL', 'department', 'region'),
        ('TM', 'department', 'region'),
        ('TM', 'district', 'department'),
        ('TN', 'department', 'region'),
        ('TN', 'district', 'department'),
        ('TN', 'municipality', 'district'),
        ('TO', 'department', 'region'),
        ('TO', 'district', 'department'),
        ('TR', 'province', 'region'),
        ('TR', 'department', 'province'),
        ('TR', 'district', 'department'),
        ('TR', 'municipality', 'district'),
        ('TT', 'province', 'region'),
        ('TT', 'department', 'province'),
        ('TW', 'province', 'region'),
        ('TW', 'department', 'province'),
        ('TW', 'county', 'department'),
        ('TW', 'district', 'county'),
        ('TW', 'municipality', 'district'),
        ('TZ', 'province', 'region'),
        ('TZ', 'department', 'province'),
        ('TZ', 'district', 'department'),
        ('TZ', 'municipality', 'district'),
        ('UA', 'province', 'region'),
        ('UA', 'department', 'province'),
        ('UA', 'district', 'department'),
        ('UA', 'municipality', 'district'),
        ('UG', 'province', 'region'),
        ('UG', 'department', 'province'),
        ('UG', 'county', 'department'),
        ('UG', 'district', 'county'),
        ('UG', 'municipality', 'district'),
        ('US', 'region', 'overseas_region'),
        ('US', 'province', 'region'),
        ('US', 'department', 'province'),
        ('US', 'county', 'department'),
        ('US', 'district', 'county'),
        ('US', 'municipality', 'district'),
        ('UY', 'province', 'region'),
        ('UY', 'department', 'province'),
        ('UY', 'municipality', 'department'),
        ('UZ', 'province', 'region'),
        ('UZ', 'department', 'province'),
        ('UZ', 'district', 'department'),
        ('VA', 'department', 'region'),
        ('VE', 'province', 'region'),
        ('VE', 'department', 'province'),
        ('VE', 'district', 'department'),
        ('VE', 'municipality', 'district'),
        ('VN', 'province', 'region'),
        ('VN', 'department', 'province'),
        ('VN', 'district', 'department'),
        ('VN', 'municipality', 'district'),
        ('VU', 'province', 'region'),
        ('VU', 'department', 'province'),
        ('WS', 'province', 'region'),
        ('XK', 'department', 'region'),
        ('YE', 'province', 'region'),
        ('YE', 'department', 'province'),
        ('YE', 'district', 'department'),
        ('ZA', 'province', 'region'),
        ('ZA', 'department', 'province'),
        ('ZA', 'district', 'department'),
        ('ZA', 'municipality', 'district'),
        ('ZM', 'province', 'region'),
        ('ZM', 'department', 'province'),
        ('ZM', 'district', 'department'),
        ('ZM', 'municipality', 'district'),
        ('ZW', 'province', 'region'),
        ('ZW', 'department', 'province'),
        ('ZW', 'district', 'department')
)
UPDATE country_admin_level child
SET parent_level_id = parent.id
FROM parent_seed ps
JOIN country c ON c.iso_code = ps.country_iso
JOIN country_admin_level parent
    ON parent.country_id = c.id
   AND parent.code = ps.parent_code
WHERE child.country_id = c.id
  AND child.code = ps.child_code;
