--liquibase formatted sql

--changeset codex:39-create-city-table dbms:postgresql
--comment Create a reusable city layer for global urban entities linked to Wikidata and optionally to territory.

CREATE TABLE IF NOT EXISTS city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country_id BIGINT NOT NULL,
    territory_id BIGINT,
    wikidata_id VARCHAR(32),
    name TEXT NOT NULL,
    description TEXT,
    latitude NUMERIC(9,6),
    longitude NUMERIC(9,6),
    population BIGINT,
    population_date DATE,
    area_km2 NUMERIC(12,3),
    inception_date DATE,
    dissolved_date DATE,
    website TEXT,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    source VARCHAR(120) NOT NULL DEFAULT 'wikidata',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_city PRIMARY KEY (id),
    CONSTRAINT fk_city_country
        FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE,
    CONSTRAINT fk_city_territory
        FOREIGN KEY (territory_id) REFERENCES territory(id) ON DELETE SET NULL,
    CONSTRAINT uq_city_wikidata_id UNIQUE (wikidata_id),
    CONSTRAINT uq_city_territory_id UNIQUE (territory_id),
    CONSTRAINT chk_city_wikidata_id CHECK (
        wikidata_id IS NULL OR wikidata_id ~ '^Q[0-9]+$'
    ),
    CONSTRAINT chk_city_population CHECK (
        population IS NULL OR population >= 0
    ),
    CONSTRAINT chk_city_area_km2 CHECK (
        area_km2 IS NULL OR area_km2 >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_city_country_id
    ON city(country_id);

CREATE INDEX IF NOT EXISTS ix_city_name
    ON city(name);

COMMENT ON TABLE city IS
'Reusable city layer for world cities. Keep stable urban attributes here instead of overloading admin_territory.';

COMMENT ON COLUMN city.territory_id IS
'Optional link to the normalized territory row when the city already exists in the gazetteer.';

COMMENT ON COLUMN city.population IS
'Latest selected population snapshot for the city.';

COMMENT ON COLUMN city.population_date IS
'Reference date attached to the selected population snapshot.';

--changeset codex:39-create-admin-territory-city-table dbms:postgresql
--comment Link administrative territories to cities with an explicit relation type.

CREATE TABLE IF NOT EXISTS admin_territory_city (
    admin_territory_id BIGINT NOT NULL,
    city_id BIGINT NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    source VARCHAR(120) NOT NULL DEFAULT 'wikidata',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_territory_city PRIMARY KEY (admin_territory_id, city_id, relation_type),
    CONSTRAINT fk_admin_territory_city_admin_territory
        FOREIGN KEY (admin_territory_id) REFERENCES admin_territory(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_territory_city_city
        FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE CASCADE,
    CONSTRAINT uq_admin_territory_city_relation
        UNIQUE (admin_territory_id, relation_type),
    CONSTRAINT chk_admin_territory_city_relation_type CHECK (
        relation_type IN ('coextensive', 'seat', 'largest_city')
    )
);

CREATE INDEX IF NOT EXISTS ix_admin_territory_city_city_id
    ON admin_territory_city(city_id);

COMMENT ON TABLE admin_territory_city IS
'Typed links between a clean administrative unit and a city, for example the administrative seat or a coextensive city.';

COMMENT ON COLUMN admin_territory_city.relation_type IS
'Meaning of the link: coextensive when the unit is the city itself, seat for the administrative capital, largest_city for the largest city.';

--changeset codex:39-create-admin-territory-city-view dbms:postgresql
--comment Convenience view joining administrative territories to their related cities.

CREATE OR REPLACE VIEW v_admin_territory_city AS
SELECT
    atc.admin_territory_id,
    at.country_id,
    country.iso_code AS country_iso2,
    country.iso3_code AS country_iso3,
    cal.code AS admin_level_code,
    cal.label AS admin_level_label,
    at.display_name AS admin_territory_display_name,
    at.admin_code AS admin_territory_code,
    atc.city_id,
    city.territory_id AS city_territory_id,
    city.wikidata_id AS city_wikidata_id,
    city.name AS city_name,
    city.description AS city_description,
    city.population,
    city.population_date,
    city.area_km2,
    city.latitude,
    city.longitude,
    city.website,
    atc.relation_type,
    atc.source
FROM admin_territory_city atc
JOIN admin_territory at ON at.id = atc.admin_territory_id
JOIN country ON country.id = at.country_id
JOIN country_admin_level cal ON cal.id = at.admin_level_id
JOIN city ON city.id = atc.city_id;
